---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# %matplotlib inline 

import numpy as np
import matplotlib.pyplot as plt
import plot_functions as pf
import pandas as pd
import xarray as xr
```

#### Open an initial dataset (observed values) from 1_generated in generate_the_Wadden_Sed.ipynb file

```{python}
ds = xr.open_dataset('wadden_sea_out.nc')
df = ds.to_dataframe()
```

take only values from the uppermost layer:

```{python}
levelcntr = df.groupby('levelcntr').get_group(0.625)
levelface = levelcntr.groupby('levelface').get_group(0)
levelface.describe()
```

```{python}
par = levelface['par'].values[0:365].astype(np.float64)
temperature = levelface['temperature'].values[0:365].astype(np.float64)
no3 = levelface['nitrate'].values[0:365].astype(np.float64)
po4 = levelface['phosphate'].values[0:365].astype(np.float64)
si = levelface['silicate'].values[0:365].astype(np.float64)
o2 = levelface['oxygen'].values[0:365].astype(np.float64)
chl_a = levelface['chl_a'].values[0:365].astype(np.float64)
om_flux = levelface['om_flux'].values[0:365].astype(np.float64)
irradiance = par*86400/1000000 # convertion microM per second to M per day
```

```{python}
ox = np.arange(1,366,1)
```

plot some data:

```{python}
# --- Select a style
plt.style.use('classic')
```

```{python}
plt.plot(ox, temperature); plt.gcf().set_size_inches(10, 2);
plt.title('Temperature, C$^{o}$');
plt.xlabel('Day'); plt.ylabel('Temperature');
```

```{python}
plt.plot(ox, par); plt.gcf().set_size_inches(10, 2);
plt.title('PAR, $\mu M\,photons\,m^{−2}\,s^{−1}$');
plt.xlabel('Day'); plt.ylabel('PAR');
```

```{python}
plt.plot(ox, chl_a); plt.gcf().set_size_inches(10, 2);
plt.title('Chl a, $mg\,Chl\,a\,m^{-3}$');
plt.xlabel('Day'); plt.ylabel('Chl a');
```

```{python}
plt.plot(ox, om_flux); plt.gcf().set_size_inches(10, 2);
plt.title('OM influx, $mg\,Chl\,a\,m^{-3}\,sec^{-1}$');
plt.xlabel('Day'); plt.ylabel('Chl a');
```

```{python}
plt.plot(ox, no3); plt.gcf().set_size_inches(10, 2);
plt.title('$NO_{3}^{-},\,\mu M$');
plt.xlabel('Day'); plt.ylabel('$NO_{3}^{-}$');
```

```{python}
plt.plot(ox, po4); plt.gcf().set_size_inches(10, 2);
plt.title('$PO_{4}^{2-},\,\mu M$');
plt.xlabel('Day'); plt.ylabel('$PO_{4}^{-}$');
```

```{python}
plt.plot(ox, si); plt.gcf().set_size_inches(10, 2);
plt.title('$Si,\,\mu M$');
plt.xlabel('Day'); plt.ylabel('$Si$');
```

```{python}
plt.plot(ox, o2); plt.gcf().set_size_inches(10, 2);
plt.title('$O_{2},\,\mu M$');
plt.xlabel('Day'); plt.ylabel('$O_{2}$');
```

#### Here we will test and visualize some functions we are going to use in the phytoplankton+biogeochemical model


Universal limiters and inhibitors:

```{python}
def linearlimiter(k, r):
    return np.minimum(r/k, 1)

def monodlimiter(ks, r):
    return (r/(r+ks))

def monodinhibitor(ks, r):
    return (ks/(ks+r))

def hyper_limiter(threshold_value, r, coef):
    return 0.5+0.5*np.tanh((r-threshold_value)*coef)

def hyper_inhibitor(threshold_value, r, coef):
    return 0.5-0.5*np.tanh((r-threshold_value)*coef)

def exp_inhibitor(ks, r):
    return np.exp(-ks*r)

def exp_limiter(ks, r):
    return 1-np.exp(-ks*r)

def sigmoid_powered(ks, r, power):
    return np.power(r, power)/(np.power(ks, power)+np.power(r, power))
```

Compare some limiters with arbitrary input parameters

```{python}
oxnut = np.arange(0, 300, 0.1)
# --- get an empty Figure and add an Axes
fig = plt.figure(figsize=(10, 4))
ax = fig.add_subplot(1, 1, 1) # row-col-num
# --- line plot data on the Axes
ax.plot(oxnut, hyper_limiter(100, oxnut, 0.1), 'b-', linewidth=2, label=r'Hyperbolic')
ax.plot(oxnut, monodlimiter(100, oxnut), 'g-', linewidth=2, label=r'Monod')
ax.plot(oxnut, sigmoid_powered(100, oxnut, 2), 'r-', linewidth=2, label=r'Sigmoid')
# --- add title and axis labels
ax.set_title('Limiters')
ax.set_ylabel(r'$ value$', fontsize=16)
ax.set_xlabel(r'$Resource, R$', fontsize=16)
# --- plot a legend in the best location
ax.legend(loc='best')
# --- add grid – not in default classic style
ax.grid(True)
# --- improve the layout
fig.tight_layout(pad=1)
```

Light limiters:

```{python}
def limlight(optimum, par):
    return (par/optimum)*np.exp(1-par/optimum)
```

Temperature limiters:

```{python}
# ersem temperature limiter doi:10.5194/gmd-9-1293-2016
def limt(q10, temperature):
    return (np.power(q10,(temperature-10)/10)
           -np.power(q10,(temperature-32)/3 ) )
```

Chl:C relationship, Cloern et al., 1995: $\frac{Chl\,a}{C} = A_{0} + A e^{BT}e^{-CI}\tau$

```{python}
def ChlCratio(temperature, irradiance, nutrient_limiter):
    """temperature - [C,
       irradiance - [mol quanta m-2 d-1]"""
    
    A0 = 0.003 # minimal Chl:C ratio
    A = 0.0154; B = 0.050; C = 0.059 # achieved by experiment
    
    return A0+A*np.exp(B*temperature)*np.exp(-1*C*irradiance)*nutrient_limiter
```

Light attenuation

```{python}
def light_attenuation(k, z, I):
    """
    k is attenuation coefficient [m-1]
    z is depth, [m]
    I is the instantaneous irradiance at depth z (PAR), [microM quanta m-2 s-1]
    or daily irradiane [mol quanta m-2 d-1]
    """
    return I*np.exp(-1*k*z)
```

Calculate nutrient limiters

```{python}
no3_limiter = sigmoid_powered(0.1, no3, 2)
si_limiter  = sigmoid_powered(0.1, si, 2)
po4_limiter = sigmoid_powered(0.1, po4, 2)
```

```{python}
# --- get an empty Figure and add an Axes
fig = plt.figure(figsize=(10, 4))
ax = fig.add_subplot(1, 1, 1) # row-col-num
# --- line plot data on the Axes
ax.plot(ox, no3_limiter, 'b-', linewidth=2, label=r'$NO_{3}^{-}$ limiter')
ax.plot(ox, po4_limiter, 'g-', linewidth=2, label=r'$PO_{4}^{2-}$ limiter')
ax.plot(ox, si_limiter, 'r-', linewidth=2, label=r'$Si$ limiter')
# --- add title and axis labels
ax.set_title('The limiters')
ax.set_ylabel(r'$limiters$', fontsize=16)
ax.set_xlabel(r'$days$', fontsize=16)
# --- plot a legend in the best location
ax.legend(loc='best')
# --- add grid – not in default classic style
ax.grid(True)
# --- improve the layout
fig.tight_layout(pad=1)
```

```{python}
nutrient_limiter = [np.min([x, y, z]) for x, y, z in zip(no3_limiter, si_limiter, po4_limiter)];
```

```{python}
ChlCratio_array = ChlCratio(temperature, light_attenuation(k=0.4, z=0.625, I=irradiance), nutrient_limiter)
```

```{python}
ox = np.arange(1,366,1)
plt.plot(ox,ChlCratio_array); plt.gcf().set_size_inches(10,2);
plt.title('Chl:C'); plt.xlabel('days'); plt.ylabel('Chl:C');
```

Photoperiod, hours

```{python}
def photoperiod():
    import datetime
    from astral import Astral
    
    city_name = 'Vilnius'
    a = Astral()
    a.solar_depression = 'civil'
    city = a[city_name]
    
    date_list = pd.date_range(start='1/1/2018', end='31/12/2018')
    sun = [city.sun(date=x, local=True) for x in date_list] 
    diff = [sun[x]['sunset']-sun[x]['sunrise'] for x in range(0,len(sun))]
    
    return [diff[x].seconds/60/60 for x in range(0,len(diff))]
```

```{python}
def photoperiod2(latitude):
    """
    From the Fennel "Marine Modelling" - page 130 and ersem zenith_angle module
    """
    
    latitude = np.pi/180*latitude
    
    a0 = 0.006918
    a1 =-0.399912
    a2 =-0.006758
    a3 =-0.002697
    b1 = 0.070257
    b2 = 0.000907
    b3 = 0.001480
    
    days = np.arange(1,366,1)
    th0 = np.pi*days/182.5
    th02 = 2*th0
    th03 = 3*th0
    
    delta =(a0
          + a1*np.cos(th0)+b1*np.sin(th0)
          + a2*np.cos(th02)+b2*np.sin(th02)
          + a3*np.cos(th03)+b3*np.sin(th03))
    
    wh = (2*np.pi)/24
    deltaday = (2/wh)*np.arccos(-np.tan(latitude)*np.tan(delta))
    
    return deltaday
```

Biomass specific photosynthetic rate, $mg\,C\,(mg\,Chl\,a\,d)^{-1}$: $P^{B} = D p^{B}_{m}(1 - \exp{\frac{I_{t} \alpha}{p^{B}_{m}}})$

```{python}
def biorate(D, pbm, alpha, I):
    """
    D is photoperiod, hours
    pbm is the maximum hourly rate of photosynthesis, [mg C (mg Chl a h)-1], by experiment
    alpha is photosynthetic efficiency at low irradiance, by experiment
    I is instanteneous irradance, PAR [microM quanta m-2 s-1]
    """
    return (D*pbm*(1-np.exp(-1*I*alpha/pbm)))
```

```{python}
photoperiod_array = np.array(photoperiod2(54.88))
biorate_array = biorate(D=photoperiod_array, pbm=8, alpha=0.05, I=light_attenuation(0.5,0.625, par))
```

```{python}
plt.plot(ox, biorate_array); plt.gcf().set_size_inches(10,2);
plt.title('Biomass specific photosynthetic rate, $mg\,C\,(mg\,Chl\,a\,d)^{-1}$');
plt.xlabel('days'); plt.ylabel('biorate');
```

Daily specific growth rate with respiration included: $\mu = R_{1} P^{B}\frac{Chl\,a}{C} - R_{0}$

```{python}
def daily_growth(biorate, ChlCratio):
    """
    Coefficiens inside evaluate respiration;
    biorate is the daily rate of photosynthesis, [mg C (mg Chl a d)-1]
    ChlCratio, joint nutrients limiter
    """
    answer = 0.85*biorate*ChlCratio-0.015
    
    return np.max([answer, 0])
    #return [np.max([0, x]) for x in answer]
```

```{python}
def excretion(kexc, phy):
    return kexc*phy

def mortality(kmrt, phy, o2):
    return phy*(kmrt+hyper_inhibitor(60, o2, 1)*0.45+hyper_inhibitor(20, o2, 1)*0.45)
```

Gross primary production

```{python}
def daily_growth_rate(kno3, ksi, kpo4, 
                      k, depth,
                      pbm, alpha,
                      no3_d, si_d, po4_d,
                      temperature_d, irradiance_d, photoperiod_d, par_d):
    """It returns net primary production, so respiration is included
       kno3, ksi, kpo4, k, pbm, alpha - parameters
       other ones - variables for the current day"""
    
    no3_limiter = sigmoid_powered(kno3, no3_d, 2)
    si_limiter  = sigmoid_powered(ksi, si_d, 2)
    po4_limiter = sigmoid_powered(kpo4, po4_d, 2)
    nutrient_limiter = np.min([no3_limiter, si_limiter, po4_limiter])
    
    ChlCratio_d = ChlCratio(temperature_d, light_attenuation(k=k, z=depth, I=irradiance_d), nutrient_limiter)
    biorate_d = biorate(D=photoperiod_d, pbm=pbm, alpha=alpha, I=light_attenuation(k=k, z=depth, I=par_d))
    daily_growth_d = daily_growth(biorate_d, ChlCratio_d)
    
    return daily_growth_d
```

```{python}
daily_growth_array = [daily_growth_rate(
                              kno3=1, ksi=0.5, kpo4=0.1,
                              k=0.04, depth=0.625,
                              pbm=8, alpha=0.05,
                              no3_d=x1, si_d=x2, po4_d=x3,
                              temperature_d=x4, irradiance_d=x5, photoperiod_d=x6, par_d=x7) 
                      for x1, x2, x3, x4, x5, x6, x7 in 
                      zip(no3, si, po4, temperature, irradiance, photoperiod_array, par)]

plt.plot(ox,daily_growth_array); plt.gcf().set_size_inches(10,2);
plt.title('Daily specific growth rate, $d^{-1}$');
plt.xlabel('days'); plt.ylabel('Daily specific growth rate');
```

Phytoplankton itself

```{python}
def c_from_ratio(chl_a, temperature, 
                 k, I, depth,
                 kno3, ksi, kpo4,
                 no3, si, po4):
    """k, depth, kno3, ksi, kpo4 - parameters"""
    
    no3_limiter = monodlimiter(kno3, no3)
    si_limiter = monodlimiter(ksi, si)
    po4_limiter = monodlimiter(kpo4, po4)
    
    nutrient_limiter = [np.min([x, y, z]) for x, y, z in zip(no3_limiter, si_limiter, po4_limiter)];
    
    return (  chl_a
            / ChlCratio(temperature, light_attenuation(k=k, z=depth, I=I), nutrient_limiter))
```

```{python}
PhyC_array = c_from_ratio(chl_a=chl_a, temperature=temperature,
                          k=0.04, I=irradiance, depth=0.625,
                          kno3=1, ksi=0.5, kpo4=0.1,
                          no3=no3, si=si, po4=po4)
```

```{python}
plt.plot(ox,PhyC_array); plt.gcf().set_size_inches(10,2);
plt.title('Phytoplankton'); plt.xlabel('days'); plt.ylabel('Phy, $mg\,C\,m^{-3}$');
```

####  Porosities

```{python}
def porosity(z, z_swi, phi_swi, phi_inf):
    k_phi = 0.04
    k = -(z-z_swi)/k_phi
    return (phi_inf+(phi_swi-phi_inf)*np.exp(k))
```

```{python}
porosity(2.505, 2.5, 0.75, 0.25)
```

```{python}
z = np.linspace(2.505, 2.595, 10)
```

```{python}
phi_inf_array = np.arange(0.05, 0.36, 0.01)
```

```{python}
phi_swi_array = np.arange(0.45, 0.86, 0.01)
```

```{python}
for phi_swi in phi_swi_array:
    for phi_inf in phi_inf_array:
        if (0.432 < sum(porosity(z, 2.5, phi_swi, phi_inf))/10 < 0.434):
            print(phi_swi, phi_inf)
```

#### Carbonates dissolution estimation

```{python}
ds = xr.open_dataset('data/low_sulfate_reduction_rate/5_po75-25_di10e-9/water.nc')
alkflux_df = ds['B_C_Alk   _flux'].to_dataframe()
biogrow_df = ds['B_BIO_GrowthPhy'].to_dataframe()
omresp_df  = ds['B_BIO_DcPOC_O2'].to_dataframe()
alk_df     = ds['B_C_Alk'].to_dataframe()
alkflux_bottom = alkflux_df.groupby('z_faces').get_group(2.5)
omresp_bottom  = omresp_df.groupby('z').get_group(2.4749999046325684)
biogrow_surfac = biogrow_df.groupby('z').get_group(0.625)
alk_surface    = alk_df.groupby('z').get_group(0.625)
alk_surface_year = alk_surface.loc['2011-01-01':'2011-12-31']
```

```{python}
year = (('2011-01-01','2011-01-31'), ('2011-02-01','2011-02-28'), ('2011-03-01','2011-03-31'), ('2011-04-01','2011-04-30'), 
        ('2011-05-01','2011-05-31'), ('2011-06-01','2011-06-30'), ('2011-07-01','2011-07-31'), ('2011-08-01','2011-08-31'),
        ('2011-09-01','2011-09-30'), ('2011-10-01','2011-10-31'), ('2011-11-01','2011-11-30'), ('2011-12-01','2011-12-31'))
```

```{python}
year_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
```

```{python}
year_acc_days = np.cumsum(year_days)
year_acc_days
```

```{python}
alk_year_delta = []
alk_year = []
bio_year = []
res_year = []
for month in year:
    alk_delta_month = alk_surface.loc[month[0]:month[1]]
    alk_month = alkflux_bottom.loc[month[0]:month[1]]
    bio_month = biogrow_surfac.loc[month[0]:month[1]]
    res_month =  omresp_bottom.loc[month[0]:month[1]]
    alk_year_delta.append(alk_delta_month['B_C_Alk'][0])
    alk_year.append(alk_month['B_C_Alk   _flux'].mean())
    bio_year.append(bio_month['B_BIO_GrowthPhy'].mean())
    res_year.append(res_month['B_BIO_DcPOC_O2'].mean())
```

```{python}
bio_year_quotas = np.array(bio_year)/sum(bio_year)
alk_year_quotas = np.array(alk_year)/sum(alk_year)
res_year_quotas = np.array(res_year)/sum(res_year)
```

```{python}
caco3_precipitation = bio_year_quotas*1000/year_days #mM
caco3_precipitation
```

```{python}
caco3_dissolution = res_year_quotas*1000/year_days
caco3_dissolution
```

```{python}
ca_flux = caco3_dissolution - caco3_precipitation
```

```{python}
ca_flux
```

```{python}
ca_array = np.array(ca_flux)/2.5*2
```

```{python}
ca_array
```

```{python}
alk_surface_year = alk_surface_year.reset_index()
alk_array = np.array(alk_surface_year['B_C_Alk'])
alkflux_bottom_year = alkflux_bottom.loc['2011-01-01':'2011-12-31']
alkflux_bottom_year = alkflux_bottom_year.reset_index()
```

#### Calculate a total increment of Ca$^{2+}$ concentration changes due to fluxes previously estimated

```{python}
calpart = np.zeros(365)
day = 0
last_entry = 0
for month, increment in zip(year_days, ca_array):
    temp = np.linspace(last_entry+increment, last_entry+increment*month, num=month)
    calpart[day:day+month] = temp
    last_entry = temp[-1]
    day += month
```

```{python}
caco3_dis = np.zeros(365)
day = 0
for month, increment in zip(year_days, caco3_dissolution):
    caco3_dis[day:day+month] = increment
    day += month
```

```{python}
caco3_pre = np.zeros(365)
day = 0
for month, increment in zip(year_days, caco3_precipitation):
    caco3_pre[day:day+month] = increment
    day += month
```

```{python}
result_array = alk_array + calpart
```

```{python}
import matplotlib.dates as mdates

plt.style.use('classic')
fig = plt.figure(figsize=(14, 4))
ax1 = fig.add_subplot(1, 2, 1) # row-col-num
ax1.xaxis_date()
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax1.plot(alk_surface_year['time'], caco3_dis*2, linewidth=2, label=r'CaCO$_3$ dissolution')
ax1.plot(alk_surface_year['time'], caco3_pre*2, linewidth=2, label=r'CaCO$_3$ precipitation')
ax1.plot(alk_surface_year['time'], alkflux_bottom_year['B_C_Alk   _flux'], linewidth=2, label=r'modelled')
ax1.plot(alk_surface_year['time'], caco3_dis*2+alkflux_bottom_year['B_C_Alk   _flux'], linewidth=2, label=r'CaCO$_3$ + modelled')
# --- add title and axis labels
#ax.set_title('Alkalinity fluxes')
ax1.set_ylabel('Flux, mmol m$^{-2}$ d$^{-1}$', fontsize=16)
#ax.set_xlabel('Month', fontsize=16)
# --- plot a legend in the best location
ax1.legend(loc='upper left', title='Alkalinity fluxes')
# --- add grid – not in default classic style
ax1.grid(True)
ax = fig.add_subplot(1, 2, 2) # row-col-num
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax.plot(alk_surface_year['time'], calpart-calpart.min(), linewidth=2, label=r'CaCO$_3$')
ax.plot(alk_surface_year['time'], alk_array-alk_array.min(), linewidth=2, label=r'modelled')
ax.plot(alk_surface_year['time'], result_array - result_array.min(), linewidth=2, label=r'CaCO$_3$ + modelled')
# --- add title and axis labels
#ax.set_title('Alkalinity fluxes')
ax.set_ylabel('TA increment, mmol m$^{-3}$', fontsize=16)
#ax.set_xlabel('Month', fontsize=16)
# --- plot a legend in the best location
ax.legend(loc='upper left', title='Alkalinity increments')
# --- add grid – not in default classic style
ax.grid(True)

fig.tight_layout(pad=1)
```

```{python}
ca_array
```

```{python}
ca_array_monthly = ca_array*year_days
ca_array_monthly
```

```{python}
alk_array = np.array(alk_year_delta)
```

```{python}
alk_array = alk_array - alk_array.min()
alk_array
```

#### Alkalinity fluxes quotas

```{python}
ds = xr.open_dataset('data/low_sulfate_reduction_rate/5_po75-25_di10e-9/water.nc')
alkflux_df = ds['B_C_Alk   _flux'].to_dataframe()
nh4flux_df = ds['B_NUT_NH4 _flux'].to_dataframe()
no2flux_df = ds['B_NUT_NO2 _flux'].to_dataframe()
no3flux_df = ds['B_NUT_NO3 _flux'].to_dataframe()
po4flux_df = ds['B_NUT_PO4 _flux'].to_dataframe()
so4flux_df = ds['B_S_SO4   _flux'].to_dataframe()
alkflux_bottom = alkflux_df.groupby('z_faces').get_group(2.5)
nh4flux_bottom = nh4flux_df.groupby('z_faces').get_group(2.5)
no2flux_bottom = no2flux_df.groupby('z_faces').get_group(2.5)
no3flux_bottom = no3flux_df.groupby('z_faces').get_group(2.5)
po4flux_bottom = po4flux_df.groupby('z_faces').get_group(2.5)
so4flux_bottom = so4flux_df.groupby('z_faces').get_group(2.5)
```

```{python}
year = (('2011-01-01','2011-01-31'), ('2011-02-01','2011-02-28'), ('2011-03-01','2011-03-31'), ('2011-04-01','2011-04-30'), 
        ('2011-05-01','2011-05-31'), ('2011-06-01','2011-06-30'), ('2011-07-01','2011-07-31'), ('2011-08-01','2011-08-31'),
        ('2011-09-01','2011-09-30'), ('2011-10-01','2011-10-31'), ('2011-11-01','2011-11-30'), ('2011-12-01','2011-12-31'))
```

```{python}
year_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
```

```{python}
alk_year = []
nh4_year = []
no2_year = []
no3_year = []
po4_year = []
so4_year = []
for month in year:
    alk_month = alkflux_bottom.loc[month[0]:month[1]]
    nh4_month = nh4flux_bottom.loc[month[0]:month[1]]
    no2_month = no2flux_bottom.loc[month[0]:month[1]]
    no3_month = no3flux_bottom.loc[month[0]:month[1]]
    po4_month = po4flux_bottom.loc[month[0]:month[1]]
    so4_month = so4flux_bottom.loc[month[0]:month[1]]
    alk_year.append(alk_month['B_C_Alk   _flux'].mean())
    nh4_year.append(nh4_month['B_NUT_NH4 _flux'].mean())
    no2_year.append(no2_month['B_NUT_NO2 _flux'].mean())
    no3_year.append(no3_month['B_NUT_NO3 _flux'].mean())
    po4_year.append(po4_month['B_NUT_PO4 _flux'].mean())
    so4_year.append(so4_month['B_S_SO4   _flux'].mean())
```

```{python}
nh4 = np.array(nh4_year)
no2 = np.array(no2_year)
no3 = np.array(no3_year)
po4 = np.array(po4_year)
so4 = np.array(so4_year)
```

```{python}
all_components = nh4-no2-no3-po4-2*so4
```

```{python}
nh4_quota = nh4/all_components
nh4_quota
```

```{python}
no2_quota = -no2/all_components
no2_quota
```

```{python}
no3_quota = -no3/all_components
no3_quota
```

```{python}
po4_quota = -po4/all_components
po4_quota
```

```{python}
so4_quota = -so4*2/all_components
so4_quota
```

```{python}
nh4_quota+no2_quota+no3_quota+po4_quota+so4_quota
```

#### Alkalinity to reduced sulfur compounds fluxes quotas

```{python}
ds1 = xr.open_dataset('data/low_sulfate_reduction_rate/2_po75-25_di1e-9/water.nc')
ds2 = xr.open_dataset('data/low_sulfate_reduction_rate/5_po75-25_di10e-9/water.nc')
ds3 = xr.open_dataset('data/low_sulfate_reduction_rate/10_po75-25_di35e-9/water.nc')
```

```{python}
ds = ds2

alkflux_df = ds['B_C_Alk   _flux'].to_dataframe()
h2s__flux_df = ds['B_S_H2S   _flux'].to_dataframe()
s0___flux_df = ds['B_S_S0    _flux'].to_dataframe()
s2o3_flux_df = ds['B_S_S2O3  _flux'].to_dataframe()

alkflux_bottom = alkflux_df.groupby('z_faces').get_group(2.5)
h2sflux_bottom  = h2s__flux_df.groupby('z_faces').get_group(2.5)
s0flux_bottom   = s0___flux_df.groupby('z_faces').get_group(2.5)
s2o3flux_bottom = s2o3_flux_df.groupby('z_faces').get_group(2.5)
```

```{python}
year = (('2011-01-01','2011-01-31'), ('2011-02-01','2011-02-28'), ('2011-03-01','2011-03-31'), ('2011-04-01','2011-04-30'), 
        ('2011-05-01','2011-05-31'), ('2011-06-01','2011-06-30'), ('2011-07-01','2011-07-31'), ('2011-08-01','2011-08-31'),
        ('2011-09-01','2011-09-30'), ('2011-10-01','2011-10-31'), ('2011-11-01','2011-11-30'), ('2011-12-01','2011-12-31'))
```

```{python}
alk_year = []
h2s_year = []
s0_year = []
s2o3_year = []
for month in year:
    alk_month = alkflux_bottom.loc[month[0]:month[1]]
    h2s_month = h2sflux_bottom.loc[month[0]:month[1]]
    s0_month = s0flux_bottom.loc[month[0]:month[1]]
    s2o3_month = s2o3flux_bottom.loc[month[0]:month[1]]
    alk_year.append(alk_month['B_C_Alk   _flux'].mean())
    h2s_year.append(h2s_month['B_S_H2S   _flux'].mean())
    s0_year.append(s0_month['B_S_S0    _flux'].mean())
    s2o3_year.append(s2o3_month['B_S_S2O3  _flux'].mean())
```

```{python}
alk = np.array(alk_year)
h2s = np.array(h2s_year)
s0 = np.array(s0_year)
s2o3 = np.array(s2o3_year)
```

```{python}
s_total = h2s + s0 + 2*s2o3
```

```{python}
alkoquota = alk*so4_quota
```

```{python}
alkoquota
```

```{python}
sulfurquota = s_total*2
```

```{python}
sulfurquota
```

#### Advection TA change

```{python}
ds = xr.open_dataset('data/advective_ta/1_10e-9/water.nc')
```

```{python}
nh4ta_df = ds['TA_due_to_NH4'].to_dataframe()
no3ta_df = ds['TA_due_to_NO3'].to_dataframe()
po4ta_df = ds['TA_due_to_PO4'].to_dataframe()
so4ta_df = ds['TA_due_to_SO4'].to_dataframe()
```

```{python}
year = (('2011-01-01','2011-01-31'), ('2011-02-01','2011-02-28'), ('2011-03-01','2011-03-31'), ('2011-04-01','2011-04-30'), 
        ('2011-05-01','2011-05-31'), ('2011-06-01','2011-06-30'), ('2011-07-01','2011-07-31'), ('2011-08-01','2011-08-31'),
        ('2011-09-01','2011-09-30'), ('2011-10-01','2011-10-31'), ('2011-11-01','2011-11-30'), ('2011-12-01','2011-12-31'))
```

```{python}
nh4ta_year = []
no3ta_year = []
po4ta_year = []
so4ta_year = []
for month in year:
    nh4ta_month = nh4ta_df.loc[month[0]:month[1]]
    no3ta_month = no3ta_df.loc[month[0]:month[1]]
    po4ta_month = po4ta_df.loc[month[0]:month[1]]
    so4ta_month = so4ta_df.loc[month[0]:month[1]]
    nh4ta_year.append(nh4ta_month['TA_due_to_NH4'].sum())
    no3ta_year.append(no3ta_month['TA_due_to_NO3'].sum())
    po4ta_year.append(po4ta_month['TA_due_to_PO4'].sum())
    so4ta_year.append(so4ta_month['TA_due_to_SO4'].sum())
```

```{python}
nh4ta = np.array(nh4ta_year)
no3ta = np.array(no3ta_year)
po4ta = np.array(po4ta_year)
so4ta = np.array(so4ta_year)
total = nh4ta+no3ta+po4ta+so4ta
```

```{python}
nh4ta
```

```{python}
no3ta
```

```{python}
po4ta
```

```{python}
so4ta
```

```{python}
total
```

```{python}
sum(so4ta)
```

```{python}
sum(total)
```

```{python}

```
