---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
import visualize as vs
```
### Introduction


The seasonal total alkalinity ($\textrm{TA}$) variations in the German bight are much larger than in the centre of the North sea (Voynova 2018, Thomas 2009).
Comparing the measured surface alkalinity values in the German bight with the calculated ones from the salinity-alkalinity relationship there are significant differences between these values (up to 250 $\mu \textrm{M}$) during a year, (see Fig. 1).
It can roughly show the importance of the coastal area processes regarding to alkalinity alteration.

```{python}
vs.plot_intro()
```

**Figure 1.** Surface water $\textrm{TA}$ measured and calculated from the alkalinity-salinity relation (Millero 1997), FerryBox measurements (54.19$^\circ$ N, 6.99$^\circ$ E, 2017)


There are several factors able to induce these differences:
  * A riverine influence.This factor is strongly geographically dependent and can cause both increase and decrease of $\textrm{TA}$ values. Since the main riverine outflow is supposed to be in the spring, we assume that this factor does not have a main importance of the presented alkalinity yearly profile with maximum in the end of the summer. Though, Neumann 2017 reports that Elbe estuary discharges brackish waters with nitrate concentrations as high as 300 $\textrm{mM}$ during winter, what can contribute to the total decrease of $\textrm{TA}$ in the German Bight (see further Eq. 1); 
  * An influence of the pelagic and benthic activities in the adjoining Wadden Sea. Thomas (2009) according to the observed alkalinity values proposed that the main driver of the seasonal southeastern North sea alkalinity variability is the alkalinity flux from the Wadden Sea;
  * An influence of the pelagic and benthic activities in the German Bight. Moore (2011) suggests not so strong input of alkalinity into the North Sea from the Wadden sea compared to the input from the North sea sediments. Brenner (2016) estimated a sedimentary alkalinity mean flux from the southern North Sea ($\textrm{SNS}$) sediments 6.6 $\pm$ 5.2 $\textrm{mM}\ \textrm{m}^{-2}\ \textrm{d}^{-1}$ in September 2011, and 5.7 $\pm$ 3.7 $\textrm{mM}\ \textrm{m}^{-2}\ \textrm{d}^{-1}$ in June 2012. Assuming average depth of the SNS is 40 m and average alkalinity mean flux is 6 $\textrm{mM}\ \textrm{m}^{-2}\ \textrm{d}^{-1}$ through the sediment-water interface ($\textrm{SWI}$) during 7 months from March until the end of September, the accumulative increase of $\textrm{TA}$ in the $\textrm{SNS}$ water column should be roughly equal to 31.5 $\textrm{mM}\ \textrm{m}^{-2}\ \textrm{d}^{-1}$ which is lower than the measured values (see Fig. 1).


At our knowledge currently, there is no study quantifying the alkalinity release and its origin in the Wadden Sea, what can be a still important source of alkalinity in the German Bight of the North Sea.
The Wadden Sea is a unique allochthonous reservoir with organic matter ($\textrm{OM}$) oxidation prevail over $\textrm{OM}$ production (Beusekom 1999, Postma 1984) inducing alkalinity generation.
Also, tidal effects cause significant mixing in this area, which can enhance alkalinity fluxes on the $\textrm{SWI}$.
Therefore, the goal of this study is to estimate the maximum value of $\textrm{TA}$ can be generated in the Wadden sea and which biogeochemical processes contribute to this value.


The “explicitly conservative form of total alkalinity” ($\textrm{TA}_{ec}$) proposed by Wolf-Gladrow (2007) contains the following terms: 

$\textrm{TA}_{ec} = [\textrm{Na}^{+}] + 2[\textrm{Mg}^{2+}] + 2[\textrm{Ca}^{2+}] + [\textrm{K}^{+}] + 2[\textrm{Sr}^{2+}] + \textrm{TNH}_{3} - [\textrm{Cl}^{-}] - [\textrm{Br}^{-}] - [\textrm{NO}_3^{-}] - \textrm{TPO}_{4} - 2\textrm{TSO}_{4} - \textrm{THF} - \textrm{THNO}_{2}$ (Eq. 1)

, where $\textrm{TNH}_{3} = [\textrm{NH}_{3}] + [\textrm{NH}_{4}^{+}]$, $\textrm{TPO}_{4} = [\textrm{H}_{3}\textrm{PO}_{4}] + [\textrm{H}_{2}\textrm{PO}_{4}^{-}] + [\textrm{HPO}_{4}^{2-}] + [\textrm{PO}_{4}^{3-}]$, $\textrm{TSO}_{4} = [\textrm{SO}_{4}^{2-}] + [\textrm{HSO}_{4}^{-}]$, $\textrm{THF} = [\textrm{F}^{-}] + [\textrm{HF}]$, and $\textrm{THNO}_{2} = [\textrm{NO}_{2}^{-}] + [\textrm{HNO}_{2}]$.


Thus increase or decrease of concentrations of any of the $\textrm{TA}_{ec}$ compounds will change alkalinity.
In anoxic conditions there are some more terms can appear in Eq. 1 ($\textrm{Fe}^{2+}$, etc.) but in presence of oxygen we assume that their contribution is cancelled since they should be oxidized and participate (Canfield 2005).
Therefore, we can consider following biogeochemical processes inducing changes of constituent elements concentrations in Eq. 1:
1. Nutrients assimilation by primary producers which includes 
  * Nitrogen uptake. Assimilation of one mole of $\textrm{NO}_{3}^{-}$ or $\textrm{NO}_{2}^{-}$ increase alkalinity by one mole, assimilation of $\textrm{NH}_{4}^{+}$ decrease alkalinity by a mole 
  * Assimilation of one mole of phosphate leads to increase of alkalinity by one mole;
2. Organic matter destruction: 
  * Oxygen respiration $(\textrm{CH}_{2}\textrm{O})_{106}(\textrm{NH}_{3})_{16}\textrm{H}_{3}\textrm{PO}_{4} + 106\textrm{O}_{2} \rightarrow 106\textrm{CO}_{2} + 16\textrm{NH}_{3} + \textrm{H}_{3}\textrm{PO}_{4} + 106\textrm{H}_{2}\textrm{O}$ increases alkalinity by 15 moles ($16\textrm{NH}_{3} - 1\textrm{H}_{3}\textrm{PO}_{4}$) per 106 moles of $\textrm{CH}_{2}\textrm{O}$ oxidized
  * Denitrification $(\textrm{CH}_{2}\textrm{O})_{106}(\textrm{NH}_{3})_{16}\textrm{H}_{3}\textrm{PO}_{4} + 84.8\textrm{HNO}_{3} \rightarrow 106\textrm{CO}_{2} + 42.4\textrm{N}_{2} + 16\textrm{NH}_{3} + \textrm{H}_{3}\textrm{PO}_{4} + 148.4\textrm{H}_{2}\textrm{O}$ increases alkalinity by 99.8 moles ($84.8\textrm{HNO}_{3} + 16\textrm{NH}_{3} - 1\textrm{H}_{3}\textrm{PO}_{4}$) per 106 moles of $\textrm{CH}_{2}\textrm{O}$ oxidized
  * Sulphate reduction $(\textrm{CH}_{2}\textrm{O})_{106}(\textrm{NH}_{3})_{16}\textrm{H}_{3}\textrm{PO}_{4} + 53\textrm{SO}_{4}^{2-} \rightarrow 106\textrm{HCO}_{3}^{-} + 16\textrm{NH}_{3} + \textrm{H}_{3}\textrm{PO}_{4} + 53\textrm{H}_{2}\textrm{S}$ increases alkalinity by 121 moles  ($2 \cdot 53 \textrm{SO}_{4}^{2-} + 16\textrm{NH}_{3} - 1\textrm{H}_{3}\textrm{PO}_{4}$) per 106 moles of $\textrm{CH}_{2}\textrm{O}$ oxidized 
  * other OM destruction reactions;
3. Nitrification due to the reaction $\textrm{NH}_{4}^{+} + 1.5\textrm{O}_{2} \rightarrow \textrm{NO}_{3}^{-} + 2\textrm{H}^{+} + \textrm{H}_{2}\textrm{O}$ decreases alkalinity by two moles;
4. Calcium carbonate precipitation $\textrm{Ca}^{2+} + 2\textrm{HCO}_{3}^{-} \rightarrow \textrm{CaCO}_{3} + \textrm{CO}_{2} + \textrm{H}_{2}\textrm{O}$ or $\textrm{Ca}^{2+} + \textrm{CO}_{3}^{-} \rightarrow \textrm{CaCO}_{3}$ induces a decrease of alkalinity by two moles per one mole of calcium carbonate precipitated and dissolution $\textrm{CaCO}_{3} + \textrm{CO}_{2} + \textrm{H}_{2}\textrm{O} \rightarrow \textrm{Ca}^{2+} + 2\textrm{HCO}_{3}^{-}$ induces an increase of alkalinity by two moles per one mole of calcium carbonate dissolved.



To estimate the changes in alkalinity it is necessary to approximate the contributions of these biogeochemical processes.
They take place in general in both the water and sediment columns.
For an instance, denitrification occurs in absence of oxygen which is often possible only in sediments, but phototrophic producers grow mostly in the water domain.
That's why we shall take into account the different domains and also parametrize the exchange between them.
On the other hand, as a first approximation, we can skip a spatial and consider only a vertical distribution since the exchange of the water and sediment domains happens mainly vertically.
Therefore to mimic some of the processes which can occur in the Wadden sea and influence $\textrm{TA}$ we can construct a vertically resolved box containing several layers of water and sediments, calculate necessary biogeochemical reactions for each layer and evaluate mixing between these layers.
In this study, we present such a model and use it to estimate the range of possible $\textrm{TA}$ production values in the Wadden Sea and to distinguish which processes prevail in different vertical mixing conditions.


### Methods


To construct the water and sediment domains grid we used the 1-d Sympagic-Pelagic-Benthic transport Model, $\textrm{SPBM}$ (Yakubov 2017) which provides an ability to calculate diffusion and sedimentation both in the water and sediments domains.
A mean depth of the Wadden Sea is 2.5 $\textrm{m}$ (Beusekom 1999), so the water domain was split into the two layers of 1.25 $\textrm{m}$ depth each and benthic boundary layer ($\textrm{BBL}$ - the layer with eddy diffusion coefficients decreasing lineary to zero on the $\textrm{SWI}$) was incorporated consisting of 2 layers of 0.05 $\textrm{m}$ depth each.
The sediments domain has 40 layers of 0.01 $\textrm{m}$ depth each.
We have not included explicit tidal dynamics into our calculations, instead, we introduced a dispersion coefficient (Boudreau 1996) in the sediment domain to reproduce different vertical mixing conditions.
Since we are interested in the $\textrm{TA}$ seasonal dynamics we set the burial velocity to zero.


To add all necessary biogeochemical processes to our calculations we constructed a biogeochemical model which is based on the empirical model of the phytoplankton Chlorophyll a $\div$ Carbon ratio (Cloern 1995) and some redox reactions partly adapted from the Bottom RedOx Model, $\textrm{BROM}$ (Yakushev 2017).
Biogeochemical model resolves only instant sinks and sources and then send increments to the transport model.
The $\textrm{SPBM}$ and biogeochemical model were linked with each other through the Framework for Aquatic Biogeochemical Models, $\textrm{FABM}$ (Bruggeman 2014).
The model was implemented in Fortran, but some parts of it were reimplemented in Python and Non-Linear Least-Square Minimization and Curve-Fitting for Python (Newville 2014) module ($\textrm{LMFIT}$) was applied for optimization.


#### 1 The Biogeochemical model


Here we will explain the most important for the $\textrm{TA}$ calculations parts of the biogeochemical model.
For the detailed description of the model see Appendix.
The main purpose of the model is to estimate the possible yearly range of the $\textrm{TA}$ fluxes on the $\textrm{SWI}$ and the corresponging $\textrm{TA}$ values in the water column of the Wadden Sea.
As a least bound of the range of the alkalinity fluxes we can apply a zero flux, so the main task is to estimate an upper bound of the alkalinity fluxes.
Here and further in all assumptions we have to make we will choose those ones which will increase the upper bound of the alkalinity fluxes, so it will help us to maybe overestimate this upper bound but not to underestimate it.

We do not separate the biogeochemical model into pelagic and benthic modules.
Instead, we use the same equations for the both domains and use functional responses and inhibitors (Soetaert 2009, page 36) to get a required behaviour when the appropriate processess happen in the appropriate conditions.
The biogeochemical model contains the following state variables: phototrophic producers ($\textrm{Phy}$), pelagic and benthic heterotrophs ($\textrm{Het}$), $\textrm{NH}_4^+$, $\textrm{NO}_2^-$, $\textrm{NO}_3^-$, $\textrm{Si}$, $\textrm{PO}_4^{3-}$, $\textrm{O}_2$, $\textrm{SO}_4^{2-}$, $\textrm{S}_2\textrm{O}_3^{2-}$, $\textrm{S}^{0}$, $\textrm{H}_2\textrm{S}$, dissolved inorganic carbon ($\textrm{DIC}$), dissolved $\textrm{OM}$ ($\textrm{DOM}$), particulate $\textrm{OM}$ ($\textrm{POM}$), dissolved organic carbon ($\textrm{DOC}$), particulate organic carbon ($\textrm{POC}$), and total alkalinity ($\textrm{TA}$).
$\textrm{OM}$ is assumed to have a Redfield stoichiometry $106\textrm{C}:16\textrm{N}:1\textrm{P}$.
The model resolves $\textrm{OM}$ production and destruction via oxygen respiration, denitrification, and sulfate reduction.
In the biogeochemical model we have implemented the $\textrm{OM}$ degradation as a two step process as in (Krumins 2013).
The first step comsumes $\textrm{OM}$ and yeilds organic carbon ($\textrm{OC}$) and nutrients (hydrolysis), the second step consumes electron acceptors and $\textrm{OC}$ and yeilds $\textrm{DIC}$ (oxidation).
We have two reactive classes for both $\textrm{OM}$ and $\textrm{OC}$: dissolved (labile) and particulate (semi-labile).
Therefore in the model semi-labile (particulate) $\textrm{OM}$ keeps an ability to sink after converting to $\textrm{OC}$.
This assumption can only increase the upper bound of $\textrm{TA}$ production since more organic reaches sediments.
Also the biogeochemical model contains nitrogen and sulfur cycles, but it does not include calcium carbonates precipitation/dissolution.
In the Wadden Sea calcium carbonate autochthonous production can serve as the upper bound of calcium carbonate dissolution since there is no allochthonous calcium carbonate input (Thomas 2009).
Therefore for the sake of clarity we have not included $\textrm{Ca}^{2+}$ in our model, calcium precipitation/dissolution can be considered separately.
The model at first calculates increments of alkalinity compounds which are involved in the biogeochemical reactions and then calculates alkalinity increment as the sum of these compounds increments: 
$$\delta [\textrm{TA}] = \delta [\textrm{NH}_4^+] - \delta [\textrm{NO}_2^-] - \delta [\textrm{NO}_3^-] - \delta [\textrm{PO}_4^{3-}] - 2\delta [\textrm{SO}_4^{2-}]$$


#### 2 Forcing, Initial and boundary conditions


The Wadden Sea is a diverse region and it is influenced by different factors in its different parts.
The riverrine influx brings not only new $\textrm{OM}$ and nutrients which can effect alkalinity related biogeochemical processes but also directly change alkalinity due to riverrine mayor ions water composition differs from seawater mayor ions composition (mixing waters can change concentrations in eq. 1).
In this study we want to consider only the local biogeochemical processes altering the alkalinity.
Therefore the data for forcing (seawater temperature, salinity, density, $\textrm{NO}_3^-$, $\textrm{Si}$, $\textrm{PO}_4^{3-}$, and $\textrm{O}_2$), initial conditions, and fitting techniques (see below) were taken from the World Ocean Database ($\textrm{WOD}$) for the 2000 - 2010 years from the rectangular 54.35-55.37$^\circ$N 6.65-8.53$^\circ$E which is an adjacent to the North Frisian Wadden Sea which has the lowest riverine and other terrestrial input.
The Wadden Sea water column is entirely mixed during a year, the vertical diffusion coefficients were calculated according to the vertical density distributions following Gargett (1984).

*Advective exchange:*
Since in our study we use the 1-dimensional transport model we have to reproduce some advective effects on the local biogeochemistry.
To do so we implemented an advective exchange of phosphates, ammonium, nitrates, and silicates within the model water column domain controlled by the advective exchange coefficient $K_{advective}$, which is a multiplier of the difference between the current state variable value and the forcing-value.
Along with concentrations profiles of corresponding elements phosphates, ammonium and nitrates exchange also affects the alkalinity according to the Eq. 1.
In presense of oxygen $\textrm{NH}_4^+$ will be inevitably oxidized to $\textrm{NO}_3^-$, therefore we assume advection waters have a zero ammonium concentrarion.

*Organic matter influx:*
To reflect a heterotrophic nature of the Wadden Sea (Postma 1954; Beusekom 1999) we have introduced an additional advective influx of $\textrm{POC}$, it represents an assumption that the entering $\textrm{POM}$ has been already processed by bacteria and decomposed to $\textrm{POC}$ and nutrients.
This $\textrm{POC}$ input was adopted from the net import of $\textrm{OM}$ to Sylt-Rømø basin value (110 $\textrm{g}\ \textrm{m}^{2}\ \textrm{year}^{-1}$) reported in (Beusekom 1999) as a sinusoidal curve with a maximum in May (Beer 2005).
This value is also close to the Wadden Sea average input (100 $\textrm{g}\ \textrm{m}^{2}\ \textrm{year}^{-1}$) from the North Sea (Beusekom 1999).

*Boundary conditions* were set up for the $\textrm{DIC}$ and $\textrm{O}_2$ on the surface boundary as an exchange with atmpsphere according to Yakushev (2017).
For all other species, boundary conditions at bottom and surface were set to zero flux.


#### 3 Parameter indentification


The resulting biogeochemical model has 56 parameters in total.
Also, we have to establish a value of the advective exchange coefficient $K_{advective}$ which in a great degree defines the $\textrm{OM}$ production in conditions of the 1-dimensional model and values of the dispersion coefficient in the sediments $kz_{dispersion}$ and porosity $\phi$ which define the vertical mixing in the sediment domain.

*Organic matter production rates derivation:* The Non-Linear Least-Squares Fitting method was applied to find the $K_{advective}$, photosynthetic efficiency at low irradiance ($\alpha$), half-saturation constants for nutrients uptake by phototrophic producers ($Ks_{PO_{4}^{3-}}$, $Ks_{Si}$, $Ks_{NH_{4}^{+}}$, $Ks_{NO_{x}}$), phototrophic producers mortality coefficient ($K_{phy\_mortality}$), and three coefficients controlling heterotrophs grazing and dying: heterotrophs grazing on primary producers rate $K_{het\_phy}$, half-saturation constant of heterotrophs to primary producers ratio $Ks_{het\_phy\_ratio}$, Heterotrophs rate of mortality $K_{het\_mortality}$.
For the detailed description see Appendix.
The chi-square statistic was constructed using $\textrm{Chlorophyll a}$ data.
After these values were obtained a new value of $K_{advective}$ was reestablished separately to make the model fit the total organic matter production (309 $\textrm{g}\ \textrm{m}^{2}\ \textrm{year}^{-1}$) in the North Frisian Wadden Sea reported by (Beusekom 1999).
The values of heterotrophs grazing on $\textrm{POM}$ rate $K_{het\_pom}$ and half-saturation constant of heterotrophs to $\textrm{POM}$ ratio $Ks_{het\_pom\_ratio}$ were not found separately, but the corresponding values for phytoplankton were adopted.
Therefore the mentioned parameters of the model were identifited to fit the seasonality of $\textrm{Chlorophyll a}$ concentrations and total yearly $\textrm{OM}$ produced in the North Frisian Wadden Sea.
Along with additional input of $\textrm{OM}$ described above we have the total $\textrm{OM}$ input during a year fit the total remineralization (419 $\textrm{g}\ \textrm{m}^{2}\ \textrm{year}^{-1}$) reported in a carbon budget of Sylt-Rømø basin by Beusekom (1999).

*Dispersion coefficient $kz_{dispersion}$ reasoning:* The Wadden sea sediments can be roughly separated into two zones with different permeabilities: sands cover $\approx 70 \%$,  and muds cover $\approx 30 \%$ (Beer 2005).
About $50 \%$ of the sediments in the Wadden Sea are exposed during low tide (Beer 2005), and tidal flats consist mostly of sands (Beer 2005, Asmus 1998).
While muds environment is reported to have higher $\textrm{OM}$ content, the sands are more permeable for electron acceptors and for new organic material from overlying water (Beer 2005).
Alkalinity generation which needs both supply of electron acceptors and $\textrm{OM}$ should occure mostly in the sands environment (with porosity $\phi \approx 0.45$ according to Beer 2005), also there can be various of advective regimes in sandy sediments.
Neumann (2017) according to nitrates advective fluxes in sediments estimations in the German Bight calculated Peclet numbers for permeable sediments, they approximately varied from 1 up to 1000.
Using a relation for dispersion offered by de Ligny (1970) (Boudreau 1997, page 138) and Peclet numbers it is possible to evaluate despersion coefficients range.
For the Peclet numbers around 1, the dispersion coefficient is approximately equal to molecular diffusion coefficient which $\approx$ $1 \cdot 10^{-9} m^{2} sec^{-1}$.
For the Peclet numbers around 1000, the dispersion coefficient is approximately 2500 times larger than the molecular diffusion coefficient.
Therefore we applied a wide range starting from 0 for $kz_{dispersion}$ in our series of runs simulating different vertical mixing conditions in sediments.
Thus we can reproduce different alkalinity fluxes from the regions of the Wadden Sea with mostly advective vertical mixing conditions in sediments to the regions with the prevailing diffusive vertical mixing.
We can not apply these calculations to the specific region since the advection conditions can change significantly within short distances, but using this approach we can achieve the possible range of values of $\textrm{TA}$ and $\textrm{TA}$ fluxes on $\textrm{SWI}$ in the Wadden Sea.


**Table 1.** Organic matter production related parameter values


| Parameter | Notation | Units | Value (Range) | Source |
|-|-|-|-|-|
| Photosynthetic efficiency at low irradiance | $\alpha$ | $\textrm{mg}\ \textrm{C}\ (\textrm{mg}\ \textrm{Chl a}\ \textrm{h})^{-1}\ (\mu M\ \textrm{quanta}\ \textrm{m}^{-2}\ \textrm{s}^{-1})^{-1}$ | 0.055 | LMFIT |
| Maximum hourly rate of photosynthesis | $p^{B}_{m}$ | $\textrm{mg}\ \textrm{C}\ (\textrm{mg}\ \textrm{Chl a}\ \textrm{h})^{-1}$ | 8 | Cloern (1995) |
| Half-saturation constant of $\textrm{PO}_4^{3-}$ uptake by $\textrm{Phy}$ | $Ks_{PO_{4}^{3-}}$ | $\textrm{mM P m}^{-3}$ | 0.17 | LMFIT |
| Half-saturation constant of $\textrm{Si}$ uptake by $\textrm{Phy}$ | $Ks_{Si}$ | $\textrm{mM Si m}^{-3}$ | 0.07 | LMFIT |
| Half-saturation constant of $\textrm{NH}_4^+$ uptake by $\textrm{Phy}$ | $Ks_{NH_{4}^{+}}$ | $\textrm{mM N m}^{-3}$ | 0.57 | LMFIT |
| Half-saturation constant of $\textrm{NO}_{2}^{-}$ and $\textrm{NO}_{3}^{-}$ uptake by $\textrm{Phy}$ | $Ks_{NO_{x}}$ | $\textrm{mM N m}^{-3}$ | 9.39 | LMFIT |
| $\textrm{Phy}$ rate of mortality | $K_{phy\_mortality}$ | $\textrm{d}^{-1}$ | 2.7e-5 | LMFIT |
| $\textrm{Phy}$ rate of excretion | $K_{phy\_excrete}$ | $\textrm{d}^{-1}$ | 0.015 | see text |
| $\textrm{Het}$ grazing on $\textrm{Phy}$ rate | $K_{het\_phy}$ | $\textrm{d}^{-1}$ | 0.136 | LMFIT |
| Half-saturation constant of $\textrm{Het}$ to $\textrm{Phy}$ ratio | $Ks_{het\_phy\_ratio}$ | $-$ | 0.219 | LMFIT |
| $\textrm{Het}$ grazing on $\textrm{POM}$ rate | $K_{het\_pom}$ | $\textrm{d}^{-1}$ | 0.136 | see text |
| Half-saturation constant of $\textrm{Het}$ to $\textrm{POM}$ ratio | $Ks_{het\_pom\_ratio}$ | $-$ | 0.219 | see text |
| $\textrm{Het}$ rate of respiration | $K_{het\_respiration}$ | $\textrm{d}^{-1}$ | 0.015 | see text |
| $\textrm{Het}$ rate of mortality | $K_{het\_mortality}$ | $\textrm{d}^{-1}$ | 0.0225 | LMFIT |
| $\textrm{Het}$ food absorbency | $Uz$ | $-$ | 0.5 | Yakushev (2017) |
| $\textrm{Het}$ ratio between dissolved and particulate excretion | $Hz$ | $-$ | 0.5 | Yakushev (2017) |
| Advective exchange coefficient | $K_{advective}$ | $-$ | 0.002 | see text |
| Vertical dispersion coefficient in sediments | $kz_{dispersion}$ | $m^2 s^{-1}$ | 1e-9 - 35e-9 | see text |
| Porosity | $\phi$ | $-$ | 0.45 | Beer (2005) |


*Organic matter destruction rates reasoning:*
$\textrm{OC}$ oxidation rate depends on the local microbial and sediments physical properties conditions.
Here we want to derive the $\textrm{OC}$ respiration rate for our specific region.
Beer (2005) investigated mineralization rates in an intertidal sand flat which is part of the Sylt-Rømø Basin in the North Frisian Wadden Sea near the German–Danish border.
The maximum value of oxygen uptake by sediments in stagnant conditions they measured was 36 $\textrm{mM O}_2\ \textrm{m}^{-2}\ \textrm{d}^{-1}$.
It is the same order as the measured maximum total oxygen uptake rate by sediments ($\approx 30\ \textrm{mM O}_2\ \textrm{m}^{-2}\ \textrm{d}^{-1}$) in the Southern North Sea (Brenner 2016).
Assuming the most of the labile organics were oxidized in the water column $\textrm{POC}$ is the most abundant type of $\textrm{OC}$ in sediments.
Therefore we have to estimate the oxygen $\textrm{POC}$ respiration rate.
Varying $\textrm{POC}$ oxygen respiration rate we found out that the most of the oxygen consumption in our model occurs actually not in the sediments, but in the lower level of $\textrm{BBL}$ and an average $\textrm{POC}$ concentration near bottom and in the upper layers of sediments is about $200000\ \textrm{mg C m}^{-3}$.
We want to derive the oxygen $\textrm{POC}$ respiration rate corresponding the oxygen uptake by sediments value (36 $\textrm{mM O}_2\ \textrm{m}^{-2}\ \textrm{d}^{-1}$) proposed by Beer (2005).
It is possible to calculate it as follows.
The depth of the $\textrm{BBL}$ layers is $5\ \textrm{cm}$.
Therefore the upper bound value of the $\textrm{OC}$ respiration per a day in the one $\textrm{BBL}$ layer considering that all oxygen is consumed only for mineralization is $\approx 36 \cdot \frac{100}{5} = 720\ \textrm{mM C m}^{-3}\ \textrm{d}^{-1}$ or $8640\ \textrm{mg C m}^{-3}\ \textrm{d}^{-1}$.
Accounting for average $\textrm{POC}$ concentration and the first order reaction parametrization with respect to $\textrm{POC}$ concentration we can estimate the yearly overall upper bound of oxygen respiration rate as $8640 \div 200000 = 0.043$.
We have a temperature $\textrm{q10}$ dependency (see Appendix) with a multiplier 2 in our $\textrm{OC}$ respiration reaction parametrization and according to the $\textrm{WOD}$ data used for the calibration the difference between temperature of maximum $\textrm{OC}$ concentration period and minimum temperature in the Wadden Sea lies within approximately $10^\circ C$.
Therefore the basic upper bound of oxygen respiration rate for the first order reaction with $\textrm{q10 = 2}$ temperature factor and temperature range of $10^\circ C$ shall be $\frac{0.043}{2} \approx 0.02$.
Since we split up a continuous process of $\textrm{OM}$ degradation to the 2 steps, the hydrolysis reaction rate can be approximated by oxidation reaction rate.
Labile organics $\textrm{DOM(C)}$ hydrolysis and oxidation rates should be larger than the rates for semi-labile organics, the typical range reported in literature of differences of labile and semi-labile organics oxidation rates is about from 10 to 100 times (Krumins 2013).
We applied the value of 10.
Since we do not know the reaction rates of denitrification and sulfate reduction we used the following reasoning to establish the upper and lower bounds for these reaction rates.
As the upper bounds, we applied the derived oxygen respiration rate which can be considered as an overestimated rate.
Krumins (2013) scales the rates of the different electron accepting pathways by their relative cell yields, we do not explicitly add this scaling in our parametrization but instead, adopt these values to scale rates of denitrification and sulfate reduction.
These values we applied as the lower (which should be closer to the 'real' conditions) bounds.


**Table 2.** Organic matter destruction related parameter values


| Parameter | Notation | Units | Value (Range) | Source |
|-|-|-|-|-|
| $\textrm{POM}$ to $\textrm{DOM}$ autolysis | $K_{pom\_dom}$ | $\textrm{d}^{-1}$ | 0.15 | Yakushev 2017 |
| $\textrm{DOM}$ in $\textrm{O}_2$ hydrolysis | $K_{O_2dom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.2 | see text |
| $\textrm{POM}$ in $\textrm{O}_2$ hydrolysis | $K_{O_2pom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.02 | see text |
| $\textrm{DOC}$ oxygen respiration | $K_{O_2doc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.2 | see text |
| $\textrm{POC}$ oxygen respiration | $K_{O_2poc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.02 | see text |
| Half-saturation constant of $\textrm{O}_2$ for $\textrm{OM}$ oxygen respiration | $Ks_{O_2}$ | $\textrm{mM O}_2\ \textrm{m}^{-3}$ | 1 | Yakushev 2017 |
| $\textrm{DOM}$ in $\textrm{NO}_3^-$ hydrolysis | $K_{NO_3^-dom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.2 | see text |
| $\textrm{POM}$ in $\textrm{NO}_3^-$ hydrolysis | $K_{NO_3^-pom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.02 | see text |
| $\textrm{DOC}$ denitrification 1st stage | $K_{NO_3^-doc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.15 - 0.2 | see text |
| $\textrm{POC}$ denitrification 1st stage | $K_{NO_3^-poc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.015 - 0.02 | see text |
| Half-saturation constant of $\textrm{NO}_3^-$ for $\textrm{OM}$ denitrification | $Ks_{NO_3^{-}}$ | $\textrm{mM NO}_3^-\ \textrm{m}^{-3}$ | 0.1 | Yakushev 2017 |
| Half-saturation constant of $\textrm{O}_2$ for $\textrm{OM}$ denitrification | $Ks_{O_2forNO_3^{-}}$ | $\textrm{mM O}_2^-\ \textrm{m}^{-3}$ | 10 | Yakushev 2017 |
| $\textrm{DOM}$ in $\textrm{NO}_2^-$ hydrolysis | $K_{NO_2^-dom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.2 | see text |
| $\textrm{POM}$ in $\textrm{NO}_3^-$ hydrolysis | $K_{NO_2^-pom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.02 | see text |
| $\textrm{DOC}$ denitrification 2st stage | $K_{NO_2^-doc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.15 - 0.2 | see text |
| $\textrm{POC}$ denitrification 2st stage | $K_{NO_2^-poc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.015 - 0.02 | see text |
| Half-saturation constant of $\textrm{NO}_2^-$ for $\textrm{OM}$ denitrification | $Ks_{NO_2^{-}}$ | $\textrm{mM NO}_2^-\ \textrm{m}^{-3}$ | 0.1 | Yakushev 2017 |
| $\textrm{DOM}$ in $\textrm{SO}_4^{2-}$ hydrolysis | $K_{SO_4^{2-}dom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.2 | see text |
| $\textrm{POM}$ in $\textrm{SO}_4^{2-}$ hydrolysis | $K_{SO_4^{2-}pom\_hydrolysis}$ | $\textrm{d}^{-1}$ | 0.02 | see text |
| $\textrm{DOC}$ sulphate reduction | $K_{SO_4^{2-}doc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.04 - 0.2 | see text |
| $\textrm{POC}$ sulphate reduction | $K_{SO_4^{2-}poc\_oxidation}$ | $\textrm{d}^{-1}$ | 0.004 - 0.02 | see text |
| Half-saturation constant of $\textrm{SO}_4^{2-}$ for $\textrm{OM}$ sulphate reduction | $Ks_{SO_4^{2-}}$ | $\textrm{mM SO}_4^{2-}\ \textrm{m}^{-3}$ | 1 | Yakushev 2017 |
| Half-saturation constant of $\textrm{O}_2$ for $\textrm{OM}$ sulphate reduction | $Ks_{O_2forSO_4^{2-}}$ | $\textrm{mM O}_2^-\ \textrm{m}^{-3}$ | 25 | Yakushev 2017 |
| Half-saturation constant of $\textrm{NO}_3^-$ for $\textrm{OM}$ sulphate reduction | $Ks_{NO_3forSO_4^{2-}}$ | $\textrm{mM NO}_3^-\ \textrm{m}^{-3}$ | 5 | Yakushev 2017 |
| Reference temperature | $T_{ref}$ | $^{\circ}$C | 2 | see text |
| Temperature factor | $q_{10}$ | $-$ | 2 | Soetaert 2009 |


The rest of the reaction parameters for anammox, nitrification, and sulphur cycle were taken from the Yakushev (2017).
Anammox do not change $\textrm{TA}$ directly, loss of nitrogen compounds is compensated by the horizontal advection reproduced in the transport model.
Due to the same reason of advection in the water column nitrification rates has a minor influence on the our assesment.
Sulfur cycle reaction rates will be discussed futher.


### Results and discussion


To estimate the range of possible $\textrm{TA}$ production values in the Wadden Sea we simplified this comprehensive region with the 1-dimensional setup.
Therefore at first, we will discuss the interpretation of the results presented below.
In the biogeochemical model we omit $\textrm{MnO}_2$ and  $\textrm{FeOOH}$ electron acceptors which are energetically more preferable then sulfate and can also oxidize sulfur compounds to sulfate.
Both can cause overestimation of $\textrm{TA}$ generation since in the first case there will be less $\textrm{OM}$ for sulfate reduction and in the second oxidizing to sulfate will decrease $\textrm{TA}$ according to Eq. 1.
Also, we have not included calcium participation and dissolution in our calculations.
According to the goal of the study there are two quantities were calculated based on the local $\textrm{OM}$ production, additional external $\textrm{OM}$ input, and $\textrm{OM}$ degradation rates in the Wadden Sea: $\textrm{TA}$ on the $\textrm{SWI}$ fluxes and $\textrm{TA}$ concentrations increments in the water column (both without accounting calcium dissolution/participation and additional terrestrial inflow influence on the $\textrm{TA}$).
Therefore the $\textrm{TA}$ fluxes can be considered as their maximum estimations, the $\textrm{TA}$ concentrations increments represent the maximum value of the accumulated alkalinity within a water mass.

```{python}
vs.plot_alkalinity_flux_low()
```

```{python}
vs.plot_alkalinity_flux_high()
```

**Figure 2.** Yearly profiles of the $\textrm{TA}$ fluxes on the $\textrm{SWI}$ of the Wadden Sea for the different advection regimes


$\textrm{TA}$ fluxes on the $\textrm{SWI}$ increase with dispersion coefficiens values (Fig. 2), according to intuition more advective regimes correspond to higher fluxes of elements including compounds of $\textrm{TA}$.
With the higher sulfate reduction rates the outflux of alkalinity from sediments to the water column starts yearlier approximately by one month.

```{python}
vs.plot_alkalinity_low()
```

```{python}
vs.plot_alkalinity_high()
```

**Figure 3.** Yearly profiles of the $\textrm{TA}$ increments (actual value minus yearly minimum value) in the surface layer of the model for the different advection regimes


In general $\textrm{TA}$ increments also growth with values of dispersion coefficient (Fig. 3), except the border values with mostly diffusive and mostly advective regimes where this relation does not work, after the value of $kz_{dispersion} \approx 25 \cdot 10^{-9}$ the value of $\textrm{TA}$ maximum does not grow in case of low sulfate reduction rates and grow very slightly in case of high sulfate reduction rates. 
The $\textrm{TA}$ increments calculated using the upped bound of sulfate reduction rates as it was observed for fluxes reach their maximum values earlier then increments caculated using the lower bound of sulfare reduction rates.


For both upper and lower bounds of sulfate reduction rates there is a time lag between maximum values of $\textrm{TA}$ fluxes and $\textrm{TA}$ increments which equals approximately 1.5 month.
The $\textrm{TA}$ increments represent the accumulated alkalinity and time of this accumulation should contribute to this delay gap.
However only this accumulation can be responsible for this delay, we have positive alkalinity effluxes for the all time of calculatioins, but the $\textrm{TA}$ values in the water column decrease durin winter.
There are the effluxes from the sediments of the other elements should be present along with alkalinity compound, and transformation of these elements change the alkalinity in the water column.

In our modelling we have sulfur compounds oxidation rates somewhat orbitrary determined according to the values from other work.
So assume how it can influence to the our estimation of the upper bound.
Let's consider 2 cases where there is the overestimated total rate of the sulfide to sulfate oxidation or there is the underestimated total rate of the sulfide to sulfate oxidation.
In the first case with the less true total oxidation rate there is should be bigger flux of alkalinity out of the $\textrm{SWI}$ (which is in fact the flux of the sulfate into the $\textrm{SWI}$) and bigger corresponding fluxes of the sulfur intermediate compounds.
The resulting delay gap between alkalinity flux and alkalinity shall be even larger since sulfur compounds are oxidized with the less rate, which is unlikely according to the measurements showing the maximum values of alkalinity are observed during summer and autumn.
In the second case with the bigger true total oxidation rate the resulting fluxes of alkalinity shall be less itself what makes our uppen bound even more overestimated.
Therefore our estimation of the upper bound of alkalinity fluxes and alkalinity values in the Wadden sea according to the reported total $\textrm{OM}$ input in this area, oxigen respiration in stagnant conditions upper bound, and the average depth of 2.5 m is consistent.

The increase of dispersion coefficient do not nesessary increase a value of alkalinity in the water column.
Changind vertical advection conditions redistribute priority of processes influence to the alkalinity distribution in the sediments and in the BBL.

```{python}
vs.plot_alkalinity_porosities()
```

```{python}
vs.plot_alkalinity_flux_porosities()
```

### Appendix - the biogeochemical model description


The model contains the following state variables: phototrophic producers, $\textrm{Phy}\ [\textrm{mg C m}^{-3}]$; pelagic and benthic heterotrophs, $\textrm{Het}\ [\textrm{mg C m}^{-3}]$; $\textrm{NH}_4^+\ [\textrm{mM N m}^{-3}]$; $\textrm{NO}_2^-\ [\textrm{mM N m}^{-3}]$; $\textrm{NO}_3^-\ [\textrm{mM N m}^{-3}]$; $\textrm{Si}\ [\textrm{mM Si m}^{-3}]$; $\textrm{PO}_4^{3-}\ [\textrm{mM P m}^{-3}]$; $\textrm{O}_2\ [\textrm{mM O}_2\ \textrm{m}^{-3}]$; $\textrm{SO}_4^{2-}\ [\textrm{mM S m}^{-3}]$; $\textrm{S}_2\textrm{O}_3^{2-}\ [\textrm{mM S m}^{-3}]$; $\textrm{S}^{0}\ [\textrm{mM S m}^{-3}]$; $\textrm{H}_2\textrm{S}\ [\textrm{mM S m}^{-3}]$; dissolved inorganic carbon, $\textrm{DIC}\ [\textrm{mM C m}^{-3}]$; dissolved $\textrm{OM}$, $\textrm{DOM}\ [\textrm{mg C m}^{-3}]$; particulate $\textrm{OM}$, $\textrm{POM}\ [\textrm{mg C m}^{-3}]$; dissolved organic carbon, $\textrm{DOC}\ [\textrm{mg C m}^{-3}]$; particulate organic carbon, $\textrm{POC}\ [\textrm{mg C m}^{-3}]$; $\textrm{TA}\ [\textrm{mM m}^{-3}]$.
$\textrm{OM}$ is assumed to have a Redfield stoichiometry $(\textrm{CH}_{2}\textrm{O})_{106}(\textrm{NH}_{3})_{16}\textrm{H}_{3}\textrm{PO}_{4}$.


#### Phototrophic producers


Phototrophic producers growth $\textrm{Phy}_{growth} = \mu \cdot[\textrm{Phy}]$ is parametrized according to the empirical equation that describes the phytoplankton daily specific growth rate $\mu\ [\textrm{d}^{-1}]$ as a function of biomass specific photosynthetic rate $P^{B}\ [\textrm{mg C (mg Chl a d)}^{-1}]$ and $\frac{Chl\,a}{C}$ ratio $[\textrm{mg Chl a (mg C)}^{-1}]$ (Cloern 1995):


$\mu = 0.85 P^{B}\frac{Chl\,a}{C} - 0.015$,

$P^{B} = D p^{B}_{m}(1 - \exp{\frac{I_{t} \alpha}{p^{B}_{m}}})$,

$\frac{Chl\,a}{C} = 0.003 + 0.0154 e^{0.050 T}e^{-0.059 I}\tau$.


Here $D$ is the photoperiod $[\textrm{h}]$ ,calculated according to (Fennel and Neumann 2004, page 130), $p^{B}_{m}$ is the maximum hourly rate of photosynthesis
normalized to chlorophyll biomass $[\textrm{mg}\ \textrm{C}\ (\textrm{mg}\ \textrm{Chl a}\ \textrm{h})^{-1}]$, $I_t$ is the istantaneous photosynthetically active radiation ($\textrm{PAR}$) $[\mu \textrm{M quanta m}^{-2}\ \textrm{s}^{-1}]$, and $\alpha$ defines photosynthetic efficiency at low irradiance $[\textrm{mg}\ \textrm{C}\ (\textrm{mg}\ \textrm{Chl a}\ \textrm{h})^{-1}\ (\mu M\ \textrm{quanta}\ \textrm{m}^{-2}\ \textrm{s}^{-1})^{-1}]$.
$T$ is the temperature $[^\circ C]$, $I$ is the daily irradiance $[\textrm{M quanta m}^{-2}\ \textrm{d}^{-1}]$, and $\tau$ is the nutrients-limited growth rate $[\textrm{d}^{-1}]$.
$\tau = \tau_{N} \tau_{Si} \tau_{PO_{4}^{3-}}$ where $\tau_{N}$ is the nitrogen-limited growth rate, $\tau_{Si}$ is he silicon-limited growth rate, and $\tau_{P}$ is the phosphorus-limited growth rate: $\tau_{N} = \tau_{NH_{4}^{+}} + \tau_{NO_{x}}$, $\tau_{NH_{4}^{+}} = f_{r}(Ks_{NH_{4}^{+}}, [$NH$_{4}^{+}])$, $\tau_{NO_{x}} = f_{r}(Ks_{NO_{x}}, [\textrm{NO}_{2}^{-}]+[\textrm{NO}_{3}^{-}]) \cdot f_{i}(Ks_{NH_{4}^{+}}, [\textrm{NH}_{4}^{+}])$; $\tau_{Si} = f_{r}(Ks_{Si}, [$Si$])$; $\tau_{PO_{4}^{3-}} = f_{r}(Ks_{PO_{4}^{3-}}, [$PO$_{4}^{3-}])$.
$f_r$ and $f_i$ are the sigmoid type functional response and inhibitor function respectively of the following forms: $f_r(Ks_R, R) = \frac{R^2}{Ks_R^2 + R^2}$ and $f_i(Ks_R, R) = \frac{Ks_R^2}{Ks_R^2 + R^2}$ where R is the limiting or inhibiting resource concentration and $Ks_R$ is the corresponding half-saturation constant.
Therefore for an instance in case of high availability of ammonium ($[\textrm{NH}_{4}^{+}] >> Ks_{NH_{4}^{+}}$) $\tau_{NH_{4}^{+}}$ tends to one while the nitrates+nitrites limiting term $\tau_{NO_{x}}$ inhibited by ammonium tends to zero.


Phototrophic producers excretion $\textrm{Phy}_{excrete} = K_{phy\_excrete} \cdot [\textrm{Phy}]$ and mortality $\textrm{Phy}_{mortality} = K_{phy\_mortality} \cdot [\textrm{Phy}] \cdot [\textrm{Phy}]$ where $K_{phy\_excrete}$ is the phytoplankton excretion coefficient and $K_{phy\_mortality}$ is the phytoplankton mortality coefficient.


#### Heterotrophs


Heterotrophs growth parametrization is based on the feeding of heterotrophs on $\textrm{Phy}$ and $\textrm{POM}$ following Yakushev (2007) approach, where carnivore feeding rate depends on prey to predator ratio:


$\textrm{Het}_{grazing\_phy} = K_{het\_phy} \cdot f_r(Ks_{het\_phy\_ratio},  \frac{[Phy]}{[Het]}) \cdot [\textrm{Het}]$,

$\textrm{Het}_{grazing\_pom} = K_{het\_pom} \cdot f_r(Ks_{het\_pom\_ratio},  \frac{[POM]}{[Het]}) \cdot [\textrm{Het}]$.


Here $K_{het\_phy}$ and $K_{het\_pom}$ are the coefficients of feeding of heterotrophs on $\textrm{Phy}$ and $\textrm{POM}$ respectively.
$Ks_{het\_phy\_ratio}$ and $Ks_{het\_pom\_ratio}$ are the half-saturation constants which determine the prey to predator ratio where the consumption rate attains 50$\%$ of its maximal value. $f_r$ is the sigmoid type functional response (see Phototrophic producers chapter).


Heterotrophs biomass loss consist of respiration and mortality parts:


$\textrm{Het}_{respiration} = K_{het\_respiration} \cdot f_{r\_hyperbolic}(Ks_{het\_oxygen}, [\textrm{O}_2]) \cdot [\textrm{Het}]$,

$\textrm{Het}_{mortality} = (K_{het\_mortality} + f_{i\_hyperbolic}(Ks_{het\_oxygen}, [\textrm{O}_2]) \cdot (1 - K_{het\_mortality})) \cdot [\textrm{Het}]$.


Here $f_{r\_hyperbolic}(Ks_R, R) = 0.5 + 0.5 \cdot \tanh(R - Ks_R)$ is the hyperbolic type functional response and $f_{i\_hyperbolic}(Ks_R, R) = 0.5 - 0.5 \cdot \tanh(R - Ks_R)$ is the hyperbolic type inhibitor function where $R$ is the limiting or inhibiting resource concentration and $Ks_R$ is the corresponding half-saturation constant as previously.
Comparing with $f_r$ and $f_i$ functions they provide a steeper gradient with R changing.
$K_{het\_respiration}$ and $K_{het\_mortality}$ are the coefficients of heterothrophs respiration and mortality respectively.
Therefore with sufficient oxygen concentrations ($[\textrm{O}_{2}] > Ks_{het\_oxygen}$) respiration and mortality of heterotrophs depend on corresponding coefficients $K_{het\_respiration}$ and $K_{het\_mortality}$, otherwise respiration tends to zero and mortality tends to be equal to the heterotrophs biomass $\textrm{[Het]}$.


#### Organic matter


Following Krumins (2013) $\textrm{OM}$ degradation is parametrised as a two-step process for all oxygen respiration, denitrification, and sulfate reduction where the first step (hydrolysis) comsumes $\textrm{OM}$ and yeilds organic carbon ($\textrm{OC}$: $\textrm{DOC}$ or $\textrm{POC}$) and nutrients and the second step (oxidation) consumes electron acceptors and $\textrm{OC}$ and yeilds $\textrm{DIC}$.
Also autolysis process introduced as a first order reaction $\textrm{OM}_{autolysis} = K_{pom\_dom} \cdot [\textrm{POM}]$.
Here in sake of simplicity we represent $\textrm{OM}$ as $\textrm{CH}_2\textrm{O}$ while in the model it is assumed to have Redfield stoichiometry as mentioned above.
The $\textrm{OM}$ oxygen respiration rates are parametrized as functions:


| Reaction | Parameterization |
|-|-|
| Oxygen respiration: | $K_{om\_respiration} = f_r(Ks_{O_2}, [\textrm{O}_2]) \cdot \tau_{10}(T, q_{10}, T_{ref})$|
| $\textrm{CH}_2\textrm{O} + \textrm{O}_2 \rightarrow \textrm{CO}_2 + \textrm{H}_2\textrm{O}$ | $\textrm{DOM}_{O_2hydrolysis} = K_{O_2dom\_hydrolysis} \cdot K_{om\_respiration} \cdot [\textrm{DOM}]$, $\textrm{POM}_{O_2hydrolysis} = K_{O_2pom\_hydrolysis} \cdot K_{om\_respiration} \cdot [\textrm{POM}]$, $\textrm{DOC}_{O_2oxidation} = K_{O_2doc\_oxidation} \cdot K_{om\_respiration} \cdot [\textrm{DOC}]$, $\textrm{POC}_{O_2oxidation} = K_{O_2poc\_oxidation} \cdot K_{om\_respiration} \cdot [\textrm{POC}]$. |


Here $K_{O_2dom\_hydrolysis}$, $K_{O_2pom\_hydrolysis}$, $K_{O_2doc\_oxidation}$, $K_{O_2poc\_oxidation}$ are the rates of corresponding processes, $f_r$ is the sigmoid type functional response (see Phototrophic producers chapter) with the half-saturation constant $Ks_{O_2}$, and $\tau_{10}(T, q_{10}, T_{ref}) = \exp{(\frac{T - T_{ref}}{10} \cdot \ln{q_{10}}})$ is the reaction rate modulator (see Soetaert 2009, page 49) where $T$ is temperature, $q_{10}$ is the factor of increase for every increase of the temperature with 10 $^{\circ} C$, and $T_{ref}$ is reference temperature at which $\tau_{10} = 1$. Therefore these processes rates are the first order temperature dependent reactions which not equal zero roughly when and where $[\textrm{O}_2] > Ks_{oxygen}$.


The $\textrm{OM}$ denitrification are splitted to the 2 stages, oxidation with nitrates on the first and oxidation with nitrites on the second stage:


| Reaction | Parameterization |
|-|-|
| 1st stage: | $K_{om\_denitrification1} = f_r(Ks_{NO_3^{-}}, [\textrm{NO}_3^{-}]) \cdot f_{i\_hyperbolic}(Ks_{O_2forNO_3^{-}}, [\textrm{O}_2])$ |
| $0.5\textrm{CH}_2\textrm{O} + \textrm{NO}_3^- \rightarrow \textrm{NO}_2^- + 0.5\textrm{H}_2\textrm{O} + 0.5\textrm{CO}_2$ | $\textrm{DOM}_{NO_3^-hydrolysis} = K_{NO_3^-dom\_hydrolysis} \cdot K_{om\_denitrification1} \cdot [\textrm{DOM}]$, $\textrm{POM}_{NO_3^-hydrolysis} = K_{NO_3^-pom\_hydrolysis} \cdot K_{om\_denitrification1} \cdot [\textrm{POM}]$, $\textrm{DOC}_{NO_3^-oxidation} = K_{NO_3^-doc\_oxidation} \cdot K_{om\_denitrification1} \cdot [\textrm{DOC}]$, $\textrm{POC}_{NO_3^-oxidation} = K_{NO_3^-poc\_oxidation} \cdot K_{om\_denitrification1} \cdot [\textrm{POC}]$. |
| 2nd stage: | $K_{om\_denitrification2} = f_r(Ks_{NO_2^{-}}, [\textrm{NO}_2^{-}]) \cdot f_{i\_hyperbolic}(Ks_{O_2forNO_3^{-}}, [\textrm{O}_2]) \cdot f_{i\_hyperbolic}(Ks_{NO_3^{-}}, [\textrm{NO}_3^-])$ |
| $0.75\textrm{CH}_2\textrm{O} + \textrm{H}^+ + \textrm{NO}_2^- \rightarrow 0.5\textrm{N}_2+ 1.25\textrm{H}_2\textrm{O} + 0.75\textrm{CO}_2$ | $\textrm{DOM}_{NO_2^-hydrolysis} = K_{NO_2^-dom\_hydrolysis} \cdot K_{om\_denitrification2} \cdot [\textrm{DOM}]$, $\textrm{POM}_{NO_2^-hydrolysis} = K_{NO_2^-pom\_hydrolysis} \cdot K_{om\_denitrification2} \cdot [\textrm{POM}]$, $\textrm{DOC}_{NO_2^-oxidation} = K_{NO_2^-doc\_oxidation} \cdot K_{om\_denitrification2} \cdot [\textrm{DOC}]$, $\textrm{POC}_{NO_2^-oxidation} = K_{NO_2^-poc\_oxidation} \cdot K_{om\_denitrification2} \cdot [\textrm{POC}]$.|


Here again $K_{NO_3^-dom\_hydrolysis}$, $K_{NO_3^-pom\_hydrolysis}$, $K_{NO_3^-doc\_oxidation}$, $K_{NO_3^-poc\_oxidation}$, $K_{NO_2^-dom\_hydrolysis}$, $K_{NO_2^-pom\_hydrolysis}$, $K_{NO_2^-doc\_oxidation}$, $K_{NO_2^-poc\_oxidation}$ are the rates of processes, $f_r$ is the sigmoid type functional response, and $f_{i\_hyperbolic}$ is the hyperbolic type inhibitor function (see Heterotrophs chapter).
$Ks_{NO_3^{-}}$, $Ks_{NO_2^{-}}$, and $Ks_{O_2forNO_3^{-}}$ are the respective half-saturation constants.
Therefore these processes of the first stage denitrification for an instance are inhibited in presence of oxygen and occure if roughly when and where $[\textrm{NO}_3^{-}] > Ks_{NO_3^-}$.


The $\textrm{OM sulfate}$ reduction rates:


| Reaction | Parameterization |
|-|-|
| Sulfate reduction: | $K_{om\_reduction} = f_r(Ks_{SO_4^{2-}}, [\textrm{SO}_4^{2-}]) \cdot \tau_{10}(T, q_{10}, T_{ref}) \cdot f_{i\_hyperbolic}(Ks_{O_2forSO_4^{2-}}, [\textrm{O}_2]) \cdot f_{i\_hyperbolic}(Ks_{NO_3forSO_4^{2-}}, [\textrm{NO}_3^{-}])$ |
| $2\textrm{CH}_2\textrm{O} + \textrm{SO}_4^{2-} \rightarrow \textrm{H}_2\textrm{S} + 2\textrm{HCO}_3^-$ | $\textrm{DOM}_{SO_4^{2-}hydrolysis} = K_{SO_4^{2-}dom\_hydrolysis} \cdot K_{om\_reduction} \cdot [\textrm{DOM}]$ $\textrm{POM}_{SO_4^{2-}hydrolysis} = K_{SO_4^{2-}pom\_hydrolysis} \cdot K_{om\_reduction} \cdot [\textrm{POM}]$ $\textrm{DOC}_{SO_4^{2-}oxidation} = K_{SO_4^{2-}doc\_oxidation} \cdot K_{om\_reduction} \cdot [\textrm{DOC}]$ $\textrm{POC}_{SO_4^{2-}oxidation} = K_{SO_4^{2-}poc\_oxidation} \cdot K_{om\_reduction} \cdot [\textrm{POC}]$|


$K_{SO_4^{2-}dom\_hydrolysis}$, $K_{SO_4^{2-}pom\_hydrolysis}$, $K_{SO_4^{2-}doc\_oxidation}$, $K_{SO_4^{2-}poc\_oxidation}$ are the rates of processes. Sulfate reduction rates are inhibited in the presense of more favorable electron acceptors (O$_2$ or/and NO$_3^-$). 


#### Nitrogen cycle


Except the denitrification described previously the biogeochemical model contains the nitrification implemented as a two step process and anammox:


| Name | Reaction | Parameterization |
|-|-|-|
| Nitrification 1st stage | $\textrm{NH}_{4}^{+} + \frac{3}{2} \textrm{O}_{2} \rightarrow \textrm{NO}_2^- + 2\textrm{H}^+ + \textrm{H}_2\textrm{O}$ | $\textrm{N}_{nitrification1} = K_{n1} \cdot f_{r\_hyperbolic}(Ks_{O_2forN}, [\textrm{O}_2]) \cdot [\textrm{NH}_4^+]$ |
| Nitrification 2st stage | $\textrm{NO}_{2}^{-} + \frac{1}{2} \textrm{O}_{2} \rightarrow \textrm{NO}_3^-$ | $\textrm{N}_{nitrification2} = K_{n2} \cdot f_{r\_hyperbolic}(Ks_{O_2forN}, [\textrm{O}_2]) \cdot [\textrm{NO}_2^-]$ |
| Anammox | $\textrm{NO}_{2}^{-} + \textrm{NH}_{4}^{+} \rightarrow \textrm{N}_2 + 2\textrm{H}_2\textrm{O}$ | $\textrm{N}_{anammox} = K_{anammox} \cdot f_{i\_hyperbolic}(Ks_{O_2forNO_3}, [\textrm{O}_2]) \cdot [\textrm{NH}_4^+] \cdot [\textrm{NO}_2^-]$ |


Here $K_{n1}$, $K_{n2}$, and $K_{anammox}$ are appropriate reaction rate velocities.


#### Sulfur cycle


Sulfur cycle reactions were implemented according to Yakushev (2017) as the second order reactions (except disproportionation which is the first order reaction) with adding functional responses to add better sustainability.


| Name | Reaction | Parameterization |
|-|-|-|
| $S^0$ disproportionation |  $4\textrm{S}^0 + 3\textrm{H}_2\textrm{O} \rightarrow 2\textrm{H}_2\textrm{S} + \textrm{S}_2\textrm{O}_3^{2-} + 2\textrm{H}^+$ | $\textrm{S}^0_{disproportionation} = K_{S\_disp} \cdot [\textrm{S}^0]$ |
| $\textrm{H}_2\textrm{S}$ oxidation with $\textrm{O}_2$ |    $2\textrm{H}_2\textrm{S} + \textrm{O}_2 \rightarrow 2\textrm{S}^0 + 2\textrm{H}_2\textrm{O}$   |   $\textrm{H}_2\textrm{S}_{O_2oxidation} = K_{H_2 SwithO_2} \cdot f_{r\_hyperbolic}(Ks_{O_2forS}, [\textrm{O}_2]) \cdot f_{r\_hyperbolic}(Ks_{H_2SforS}, [\textrm{H}_2\textrm{S}]) \cdot [\textrm{H}_2\textrm{S}] \cdot [\textrm{O}_2]$ |
| $\textrm{S}^0$ oxidation with $\textrm{O}_2$ | $2\textrm{S}^0 + \textrm{O}_2 + \textrm{H}_2\textrm{O} \rightarrow \textrm{S}_2\textrm{O}_3^{2-} + 2\textrm{H}^+$ | $\textrm{S}^0_{O_2oxidation} = K_{S^0 SwithO_2} \cdot f_{r\_hyperbolic}(Ks_{O_2forS}, [\textrm{O}_2]) \cdot [\textrm{S}^0] \cdot [\textrm{O}_2]$ |
|$\textrm{S}_2\textrm{O}_3^{2-}$ oxidation with $\textrm{O}_2$ | $\textrm{S}_2\textrm{O}_3^{2-} + 2\textrm{O}_2 + 2\textrm{OH}^- \rightarrow 2\textrm{SO}_4^{2-} + \textrm{H}_2\textrm{O}$ | $\textrm{S}_2\textrm{O}^{2-}_{3\_O_2oxidation} = K_{S_2O_3^{2-}withO_2} \cdot f_{r\_hyperbolic}(Ks_{O_2forS}, [\textrm{O}_2])\cdot  [\textrm{S}_2\textrm{O}_3^{2-}] \cdot [\textrm{O}_2]$ |
| Thiodenitrification | $5\textrm{H}_2\textrm{S} + 8\textrm{NO}_3^- + 2\textrm{OH}^- \rightarrow 5\textrm{SO}_4^{2-} + 4\textrm{N}_2 + 6\textrm{H}_2\textrm{O}$ | $\textrm{H}_2\textrm{S}_{NO^-_3oxidation} = K_{H_2 SwithNO_3^-} \cdot f_{r\_hyperbolic}(Ks_{NO_3^-forS}, [\textrm{NO}_3^-])\cdot f_{r\_hyperbolic}(Ks_{H_2SforS}, [\textrm{H}_2\textrm{S}]) \cdot [\textrm{H}_2\textrm{S}] \cdot [\textrm{NO}_3^-]$ |
| $\textrm{S}^0$ oxidation with $\textrm{NO}_3^-$ | $4\textrm{S}^0 + 3\textrm{NO}_3^- + 7\textrm{H}_2\textrm{O} \rightarrow 4\textrm{SO}_4^{2-} + 3\textrm{NH}_4^+ + 2\textrm{H}^+$ | $\textrm{S}^0_{NO_3^-oxidation} = K_{S^0 SwithNO_3^-} \cdot f_{r\_hyperbolic}(Ks_{NO_3^-forS}, [\textrm{NO}_3^-]) \cdot [\textrm{S}^0] \cdot [\textrm{NO}_3^-]$ |
|$\textrm{S}_2\textrm{O}_3^{2-}$ oxidation with $\textrm{NO}_3^-$| $\textrm{S}_2\textrm{O}_3^{2-} + \textrm{NO}_3^-  + 2\textrm{H}_2\textrm{O} \rightarrow 2\textrm{SO}_4^{2-} + \textrm{NH}_4^+$ | $\textrm{S}_2\textrm{O}^{2-}_{3\_NO^-_3oxidation} = K_{S_2O_3^{2-}withNO_3^-} \cdot f_{r\_hyperbolic}(Ks_{NO_3^-forS}, [\textrm{NO}_3^-]) \cdot  [\textrm{S}_2\textrm{O}_3^{2-}] \cdot [\textrm{NO}_3^-]$ |


#### Mass balance equations


The resulting change of concentration of each state variable is a sum of the relevant processes.

Let's introduce some new notation: $\textrm{DOM}_{N\_hydrolysis} = \textrm{DOM}_{NO_3^-hydrolysis} + \textrm{DOM}_{NO_2^-hydrolysis}$, $\textrm{POM}_{N\_hydrolysis} = \textrm{POM}_{NO_3^-hydrolysis} + \textrm{POM}_{NO_2^-hydrolysis}$, $\textrm{DOC}_{N\_oxidation} = \textrm{DOC}_{NO_3^-oxidation} + \textrm{DOC}_{NO_2^-oxidation}$, $\textrm{POC}_{N\_oxidation} = \textrm{POC}_{NO_3^-oxidation} + \textrm{POC}_{NO_2^-oxidation}$ 
and $\textrm{N}_{denitrification1} = 2 \cdot (\textrm{DOC}_{NO_3^-oxidation} + \textrm{POC}_{NO_3^-oxidation})$, $\textrm{N}_{denitrification2} = \frac{4}{3} \cdot (\textrm{DOC}_{NO_2^-oxidation} + \textrm{POC}_{NO_2^-oxidation})$.
The coefficients appear due to the reactions mentioned in the Organic matter chapter.

Below we will mark with superscript $'$ the processes with concentrations converted to molar, for an istance $\textrm{Phy'}_{growth}\ [mM\ C\ m^{-3}\ d^{-1}] = \frac{1}{12.011} \textrm{Phy}_{growth}\ [mg\ C\ m^{-3}\ d^{-1}]$.
Also we will mark with superscript $''$ the processes with concentrations converted according to the Redfield stoichiometry (quantity is marked with a respective subscript, carbon to silicon ratio is 106 to 15), for an instance $\textrm{DOM''}_{N\ O_2hydrolysis}\ [mM\ N\ m^{-3}\ d^{-1}] = \frac{1}{12.011} \frac{16}{106} \textrm{DOM}_{O_2hydrolysis}\ [mg\ C\ m^{-3}\ d^{-1}]$.

Consumption of nitrogen species by phototrophic producers depends on respective nitrogen-limited growth rate compounds.
Recall that $\tau_{N} = \tau_{NH_{4}^{+}} + \tau_{NO_{x}}$ where $\tau_{N}$ can not exceed 1 and $\tau_{NO_{x}}$ depends on sum of nitrites and nitrates (see phototrophic producers chapter).
Therefore ammonium by phototrophic producers consumption is $\textrm{Phy''}_{NH_4^+} = \textrm{Phy''}_{growth} \frac{\tau_{NH_{4}^{+}}}{\tau_{N}}$, 
nitrites consumption is $\textrm{Phy''}_{NO_2^-} = \textrm{Phy''}_{growth} \frac{\tau_{NO_{x}}}{\tau_{N}} \frac{[\textrm{NO}_2^-]}{[\textrm{NO}_2^-] + [\textrm{NO}_3^-]}$,
and nitrates consumption is $\textrm{Phy''}_{NO_3^-} = \textrm{Phy''}_{growth} \frac{\tau_{NO_{x}}}{\tau_{N}} \frac{[\textrm{NO}_3^-]}{[\textrm{NO}_2^-] + [\textrm{NO}_3^-]}$.

We assume that only a part ($Uz$) of total $\textrm{OM}$ consumed by heterotrophs is absorbed, also $Hz$ is a ratio between dissolved and particulate parts of heterotrophs excreted $\textrm{OM}$.
Therefore $\textrm{Het}_{grazing\_raw} = \textrm{Het}_{grazing\_phy} + \textrm{Het}_{grazing\_pom}$ and amount of organic consumed by heterotrophs is $\textrm{Het}_{grazing} = Uz \cdot \textrm{Het}_{grazing\_raw}$.
Corresponding $\textrm{DOM}$ input is $\textrm{Het}_{dom\_excrete} = \textrm{Het}_{grazing\_raw} \cdot (1 - Uz) \cdot Hz$ and $\textrm{POM}$ input is $\textrm{Het}_{pom\_excrete} = \textrm{Het}_{grazing\_raw} \cdot (1 - Uz) \cdot (1 - Hz)$.


| Model mass balance equations|
|-|
| $\delta [\textrm{Phy}] = \textrm{Phy}_{growth} - \textrm{Phy}_{mortality} - \textrm{Phy}_{excrete} - \textrm{Het}_{grazing\_phy}$ |
| $\delta [\textrm{Het}] = \textrm{Het}_{grazing} - \textrm{Het}_{respiration} - \textrm{Het}_{mortality}$ |
| $\delta [\textrm{DOM}] = \textrm{OM}_{autolysis} + \textrm{Het}_{dom\_excrete} + \textrm{Phy}_{excrete} - \textrm{DOM}_{O_2hydrolysis} - \textrm{DOM}_{N\_hydrolysis} -  \textrm{DOM}_{SO_4hydrolysis}$ |
| $\delta [\textrm{POM}] = \textrm{Phy}_{mortality} + \textrm{Het}_{mortality} + \textrm{Het}_{pom\_excrete} - \textrm{OM}_{autolysis} - \textrm{POM}_{O_2hydrolysis} - \textrm{POM}_{N\_hydrolysis} -  \textrm{POM}_{SO_4hydrolysis} - \textrm{Het}_{grazing\_pom}$ |
| $\delta [\textrm{DOC}] = \textrm{DOM}_{O_2hydrolysis} + \textrm{DOM}_{N\_hydrolysis} +  \textrm{DOM}_{SO_4hydrolysis} - \textrm{DOC}_{O_2oxidation} - \textrm{DOC}_{N\_oxidation} - \textrm{DOC}_{SO_4oxidation}$ |
| $\delta [\textrm{POC}] = \textrm{POM}_{O_2hydrolysis} + \textrm{POM}_{N\_hydrolysis} +  \textrm{POM}_{SO_4hydrolysis} - \textrm{POC}_{O_2oxidation} - \textrm{POC}_{N\_oxidation} - \textrm{POC}_{SO_4oxidation}$ |
| $\delta [\textrm{DIC}] = \textrm{Het'}_{respiration} + \textrm{DOC'}_{O_2oxidation} + \textrm{POC'}_{O_2oxidation} + \textrm{DOC'}_{N\_oxidation} + \textrm{POC'}_{N\_oxidation} + \textrm{DOC'}_{SO_4oxidation} + \textrm{POC'}_{SO_4oxidation} - \textrm{Phy'}_{growth}$ |
| $\delta [\textrm{O}_2] = \textrm{Phy'}_{growth} - \textrm{Het'}_{respiration} - \textrm{DOC'}_{O_2oxidation} - \textrm{POC'}_{O_2oxidation} - \frac{3}{2} \textrm{N}_{nitrification1} - \frac{1}{2} \textrm{N}_{nitrification2} - \frac{1}{2} \textrm{H}_2\textrm{S}_{O_2oxidation} - \frac{1}{2} \textrm{S}^0_{O_2oxidation} - 2\textrm{S}_2\textrm{O}^{2-}_{3\_O_2oxidation}$ |
| $\delta [\textrm{NH}_4^+] = \textrm{Het''}_{N\ respiration} + \textrm{DOM''}_{N\ O_2hydrolysis} + \textrm{POM''}_{N\ O_2hydrolysis} + \textrm{DOM''}_{N\ N\_hydrolysis} + \textrm{POM''}_{N\ N\_hydrolysis} +  \textrm{DOM''}_{N\ SO_4hydrolysis} +  \textrm{POM''}_{N\ SO_4hydrolysis} + \frac{3}{4} \textrm{S}^0_{NO_3^-oxidation} + \textrm{S}_2\textrm{O}^{2-}_{3\_NO^-_3oxidation} - \textrm{N}_{nitrification1} - \textrm{N}_{anammox} - \textrm{Phy''}_{NH_4^+}$ |
| $\delta [\textrm{NO}_2^-] = \textrm{N}_{nitrification1} + \textrm{N}_{denitrification1} - \textrm{N}_{nitrification2} - \textrm{N}_{denitrification2} - \textrm{N}_{anammox} - \textrm{Phy''}_{NO_2^-}$ |
| $\delta [\textrm{NO}_3^-] = \textrm{N}_{nitrification2} - \textrm{N}_{denitrification1} - \textrm{Phy''}_{NO_3^-} - \frac{8}{5} \textrm{H}_2\textrm{S}_{NO^-_3oxidation} - \frac{3}{4} \textrm{S}^0_{NO_3^-oxidation} - \textrm{S}_2\textrm{O}^{2-}_{3\_NO^-_3oxidation}$ |
| $\delta [\textrm{PO}_4^{3-}] = \textrm{Het''}_{P\ respiration} + \textrm{DOM''}_{P\ O_2hydrolysis} + \textrm{POM''}_{P\ O_2hydrolysis} + \textrm{DOM''}_{P\ N\_hydrolysis} + \textrm{POM''}_{P\ N\_hydrolysis} +  \textrm{DOM''}_{P\ SO_4hydrolysis} +  \textrm{POM''}_{P\ SO_4hydrolysis} - \textrm{Phy''}_{P\ growth}$ |
| $\delta [\textrm{Si}] = \textrm{Het''}_{Si\ respiration} + \textrm{DOM''}_{Si\ O_2hydrolysis} + \textrm{POM''}_{Si\ O_2hydrolysis} + \textrm{DOM''}_{Si\ N\_hydrolysis} + \textrm{POM''}_{Si\ N\_hydrolysis} +  \textrm{DOM''}_{Si\ SO_4hydrolysis} +  \textrm{POM''}_{Si\ SO_4hydrolysis} - \textrm{Phy''}_{Si\ growth}$ |
| $\delta [\textrm{SO}_4^{2-}] = 2\textrm{S}_2\textrm{O}^{2-}_{3\_O_2oxidation} + \textrm{H}_2\textrm{S}_{NO^-_3oxidation} + \textrm{S}^0_{NO_3^-oxidation} + 2\textrm{S}_2\textrm{O}^{2-}_{3\_NO^-_3oxidation} - \frac{1}{2} \textrm{DOC'}_{SO_4oxidation} - \frac{1}{2} \textrm{POC'}_{SO_4oxidation}$ |
| $\delta [\textrm{S}_2\textrm{O}^{2-}_{3}] = \frac{1}{4} \textrm{S}^0_{disproportionation} + \frac{1}{2} \textrm{S}^0_{O_2oxidation} - \textrm{S}_2\textrm{O}^{2-}_{3\_O_2oxidation} - \textrm{S}_2\textrm{O}^{2-}_{3\_NO^-_3oxidation}$ |
| $\delta [\textrm{S}^0] = \textrm{H}_2\textrm{S}_{O_2oxidation} - \textrm{S}^0_{disproportionation} - \textrm{S}^0_{O_2oxidation} - \textrm{S}^0_{NO_3^-oxidation}$ |
| $\delta [\textrm{H}_2\textrm{S}] = \frac{1}{2} \textrm{S}^0_{disproportionation} + \frac{1}{2} \textrm{DOC'}_{SO_4oxidation} + \frac{1}{2} \textrm{POC'}_{SO_4oxidation} - \textrm{H}_2\textrm{S}_{O_2oxidation} - \textrm{H}_2\textrm{S}_{NO^-_3oxidation}$ |
| $\delta [\textrm{TA}] = \delta [\textrm{NH}_4^+] - \delta [\textrm{NO}_2^-] - \delta [\textrm{NO}_3^-] - \delta [\textrm{PO}_4^{3-}] - 2\delta [\textrm{SO}_4^{2-}]$ |


Therefore we calculate the resulting $\textrm{TA}$ change as a sum of increments of ammonium, nitrites, nitrates, phosphates, and sulfates.

```{python}

```
